### ISSUE TITLE
Radao.org blocked for no reason

### ISSUE THREAD

**Issue by g0at** [phantom/blocklist#1001]
Hi,
our website radao.org (https://app.radao.org/) is blocked by Phantom : 

![photo_2024-03-06_11-41-53 (2)](https://github.com/phantom/blocklist/assets/121176795/86bdc1dd-2077-4249-8cf4-71d6df29527a)

What can be done to solve this problem?

Best regards

**Comment by Harii94** [comment]
Please send an email to review@blowfish.xyz for further investigation.
