### ISSUE TITLE
dollarzero.app is blocked, please unblock

### ISSUE THREAD

**Issue by DollarZero** [phantom/blocklist#1042]
Website: http:/dollarzero.app
Twitter: https://twitter.com/doolarzero
Telegram: t.me/doolarzero

Our website has been blocked on phantom app as a phishing website/scam. However no such report has been filed by a community member. Our website is simply used for completing twitter task and rewarding users memecoin tokens.

5000+ users have been using our website and none of them have reported of any security breach or loss of assets from their phantom wallets.

Kindly fix this as soon as possible because it affects our project growth.

**Comment by DollarZero** [comment]
Email sent to review@blowfish.xyz

**Comment by Harii94** [comment]
Closing this request as the site in question is no longer blocked.
