### ISSUE TITLE
https://smt.solana-suite.org is safe

### ISSUE THREAD

**Issue by fukaoi** [phantom/blocklist#1043]
URL: https://smt.solana-suite.org/
Site name: SMT

SMT is an open-source project that allows for the issuance of SPL tokens and NFTs for free, enabling users to experience tokenization. I'm baffled as to why it's been blocked, as the reason is unclear. I would like it to be unblocked.

**Comment by Harii94** [comment]
Please send an email to review@blowfish.xyz for further investigation.
