### ISSUE TITLE
1intro.org is incorrectly blocked (please help to solve, thank you)

### ISSUE THREAD

**Issue by 1intro** [phantom/blocklist#1048]
Hi team,

1INTRO is the first Liquidity Bootstrapping Pool (LBP) platform on Solana which is going to be launched in the near future. However, another domain **1intro.org** of us was incorrectly blocked by phantom, but it cannot be found in any of the three blocklist files in the codebase (blocklist.yaml, fuzzylist.yaml, and whitelist.yaml).

Please help to have a look and solve it, thank you!

**1intro website**: https://www.1intro.com/
**1intro twitter**: https://twitter.com/1intro (around 150K followers as of now)
**1intro telegram**: https://t.me/oneintrochat

Thanks & Regards
1intro Team

**Comment by Harii94** [comment]
Please send an email to review@blowfish.xyz for further investigation.
