### ISSUE TITLE
Malicious website misreport: bitgetapp.com

### ISSUE THREAD

**Issue by stevenliou** [phantom/blocklist#1051]
<img width="828" alt="截屏2024-03-26 下午9 42 11" src="https://github.com/phantom/blocklist/assets/9360792/21131d30-5369-4c82-9cc0-bf04d68c4f94">
www.bitgetapp.com
i don't think this is a scam link. i follow this link from the mail sent from notification@promo.bitget.com. and my Anti-phishing code is on the top of the mail.
pls check it!

**Comment by Harii94** [comment]
Please send an email to review@blowfish.xyz for further investigation.
