### ISSUE TITLE
phishing network

### ISSUE THREAD

**Issue by kanasite** [phantom/blocklist#1077]
coinchanger.nl - phishing exchange
ethereumixer.com - phishing mixer
bitmixing.xyz - phishing mixer
cryptomixer.ink - phishing mixer
btc-laundry.ink - phishing mixer
anonymixer.ink - phishing mixer
sec-qr-btc-eth.com - phishing qr code generator
qrforbtceth.net - phishing qr code generator

**Comment by aabatis** [comment]
Dear Mr. Kanasite,

I hope you are doing well. I would like to provide clarification regarding the blocking of the following websites:

coinchanger.nl
ethereumixer.com
bitmixing.xyz
cryptomixer.ink
btc-laundry.ink
anonymixer.ink
sec-qr-btc-eth.com
qrforbtceth.net
Reason for Blocking:

These websites have been identified as phishing platforms aimed at deceiving users into compromising their sensitive information or assets. They either masquerade as legitimate cryptocurrency services or generate fraudulent QR codes to mislead users, resulting in financial losses.

Clarification on Secure Token (SEC):

We understand that your Secure Token (SEC) "CxLtYHNZ6mwHieVi7VimVgE4QQQ2wyexfNJ8AGNG1rk2" is a legitimate project utilizing blockchain for encryption processes with new techniques, combining cybersecurity and blockchain technologies. We acknowledge your active preparation in the necessary steps to ensure its secure and compliant operation.

Given this context, and to differentiate your Secure Token from the aforementioned malicious websites, we request further verification and details about your token and its operations. This information will assist us in accurately evaluating your request to remove any blocks associated with Secure Token SEC.

Please provide the necessary documentation or any additional information at your earliest convenience. We are committed to working with you to ensure a secure and trustworthy digital environment.

Thank you for your understanding and cooperation.

Best regards,
Abdulmajid Batis the owner of token SEC
