### ISSUE TITLE
Site incorrectly flagged as malicious or unsafe

### ISSUE THREAD

**Issue by gimpey** [phantom/blocklist#1087]
Hello, both our staging website and production (non-active) site have been flagged as potentially malicious or unsafe. We're entering our closed beta and the site has not been publicy shared yet so I'm not sure how it made it onto a "community-maintained database" but aside, if you could please reach out to have it removed from this list that'd be great.

I'm a prominent developer in the OG ETH space and newly SOL. I've launched over 40 projects and am currently in development of a set of tools for the SOL environment.

Dev Team: pr0xy.io
Email: gimpey@pr0xy.io
Site: gimpey.com

I will include a direct link to the site via email communications with your team as the staging site and non-active production site are currently private (password protected). The base site is gimpey.com, the closed beta is on a subdomain.

**Comment by Harii94** [comment]
Closing this request as the site in question is no longer blocked.
