### ISSUE TITLE
Remove false block on megadicetoken.com

### ISSUE THREAD

**Issue by Tanzooga** [phantom/blocklist#1095]
Hello. 

I am writing to resolve an issue on our website megadicetoken.com. This token is launched with our existing product megadice.com . To show the legitimity of this business, presale.megadice.com is forwarding to the same content as megadicetoken.com . It seems that the domain is not actually on the blocklist, can this be related to the solana wallet connect, or the domain age? 

Would be greatly appreciated to have the false block removed / domain whitelisted. If there is further information you need, you can contact us on help@megadice.com , where you can also check the legitimacy of our business. 

Thanks already in advance.

**Comment by Harii94** [comment]
Closing this request as the site in question is no longer blocked.
