### ISSUE TITLE
 [Legitimate Site Blocked] wat.meme

### ISSUE THREAD

**Issue by WATMEMESOL** [phantom/blocklist#1106]
https://wat.meme

______

NOTE: 

Metamask found nothing malicious and unblocked it.

https://github.com/MetaMask/eth-phishing-detect/issues/48460

**Comment by WATMEMESOL** [comment]
Just to be aware, MetaMask was professional and swiftly resolved the matter. Phantom hasn't resolved this issue and it's taking too long.

https://github.com/MetaMask/eth-phishing-detect/issues/48460#event-12539404898

**Comment by Harii94** [comment]
Please drop an email to [review@blowfish.xyz](mailto:review@blowfish.xyz) to investigate further.
