### ISSUE TITLE
unblock   app-boomerang.trade -  it is a legitimate site 

### ISSUE THREAD

**Issue by Fitzy57** [phantom/blocklist#1107]
please open  app-boomerang.trade   it is a legitimate site , I and many others are using it & it is no a scam & is just going live so how it can be classed as dangerous is beyond me

Fitzy

**Comment by gothepies** [comment]
Yes the Dapp for Boomerang AI Trading is very legitimate.  We have been in Beta Phase for the last few months.  MVP is in the next 48 hours.  This address https://app-boomerang.trade/ is NOT A SCAM.
![Screenshot 2024-04-23 093314](https://github.com/phantom/blocklist/assets/167826328/75f7de3f-ecbe-4c43-9f6c-a291e5db8225)
![Screenshot 2024-04-23 093314](https://github.com/phantom/blocklist/assets/167826328/2b604aa1-94dd-4bd2-9e98-adcf4162ff80)

**Comment by thomasrgrant** [comment]
Works like a charm. Make the website unblocked.

**Comment by Harii94** [comment]
Please drop an email to review@blowfish.xyz to investigate further.

**Comment by tradercentral** [comment]
Please open this site why is it blocked ?

**Comment by Kryptoangel** [comment]
app-boomerang.trade 
Is facility providers for arbitrage trading pool protocal and not scammer.. Lots or people as community use it.. Pl don't bolock it.

**Comment by Kryptoangel** [comment]
Please open this Daap link...why is it blocked???

**Comment by Tirosnet** [comment]
Yes it SCAM 💯 %!!!

**Comment by Fitzy57** [comment]
> Yes it SCAM 💯 %!!!

How do you know that? How is it a scam? have you used it ?
