### ISSUE TITLE
unblock plsx mypinata url https://pulsex.mypinata.cloud/

### ISSUE THREAD

**Issue by jacurutu-antoineb** [phantom/blocklist#1109]
Site blocked by phantom (https://pulsex.mypinata.cloud/ipfs/bafybeidea3ibq4lu5t6vk6ihp4iuznjb3ltsdm5y2shv4atxgyd3d33aim/#/farms).

This is an IPFS link for the PLSX DEX on Pulsechain.com

I don't know why phantom is blocking anything - and I can't find a feature in settings to turn that off

**Comment by Harii94** [comment]
This is resolved now. 

Apologies for any inconvenience this might have caused you 🙏
