### ISSUE TITLE
unblock dump.trade

### ISSUE THREAD

**Issue by dump-trade** [phantom/blocklist#1110]
Hello, our webapp has been blocked and need to be unblocked, thanks!

website: https://dump.trade
docs: https://docs.dump.trade
tg: https://t.me/dump_trade

**Comment by Nivanary** [comment]
> Hello, our webapp has been blocked and need to be unblocked, thanks!
> 
> website: https://dump.trade docs: https://docs.dump.trade tg: https://t.me/dump_trade

Contact the Defi Protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [DEFI PROTOCOL](https://accessonlinedefiprotocol.web.app/)

**Comment by Harii94** [comment]
Closing this request as the site in question is no longer blocked.
