### ISSUE TITLE
Potential False Positive on public IPFS gateway

### ISSUE THREAD

**Issue by huntertdiamond** [phantom/blocklist#1112]
Hey, 
This is my first time seeing the notice, so first I want to say how awesome it is that this exists and to thank you all for building something that people will hopefully _never_ see, but save them if they do.

I think the default public gateway for ipfs (`ipfs.io/ipfs/{cid}`) is triggering a false positive. I took a look at the `blocklist.yaml` file, and nothing came up when I searched for ipfs

The exact link that triggered the warning is 
`https://ipfs.io/ipfs/QmPiUqt9twpDjfeWLyk5Nwjg7sEzuNouDx1cqtjUvn5kTW/2728`

The [IFPS docs](https://docs.ipfs.tech/concepts/public-utilities/#public-ipfs-gateways) have the same base url 
of `https://ipfs.io`

Thanks again!

**Comment by Harii94** [comment]
Closing this request as the site in question is no longer blocked.
