### ISSUE TITLE
eigenfoundation.org is blocked!

### ISSUE THREAD

**Issue by excbrp** [phantom/blocklist#1117]
eigenfoundation.org is incorrectly blocked.

Its the official claims page:

https://x.com/eigenlayer/status/1785001011003920868
https://x.com/eigenfoundation/status/1785000100315504776

**Comment by Punt13140** [comment]
I confirm, the eligibility page https://claims.eigenfoundation.org/ is blocked.

**Comment by Harii94** [comment]
Closing this request as the site in question is no longer blocked.
