### ISSUE TITLE
streamzonbase.com is blocked

### ISSUE THREAD

**Issue by benny-conn** [phantom/blocklist#1121]
Hi there,

It looks like streamzonbase.com is being blocked by phantom wallet but is the correct website for the Streamz token. The contract address is `base:0x499A12387357e3eC8FAcc011A2AB662e8aBdBd8f` and twitter is `@streamzonbase`. They posted the correct link in their most recent announcement.

Best,
Benny

**Comment by Harii94** [comment]
Closing this request as the site in question is no longer blocked.
