### ISSUE TITLE
nyxiaai.com falsely blocked

### ISSUE THREAD

**Issue by heikoles3000** [phantom/blocklist#1122]
Hi we are Nyxia AI and building currently our AI app where you can generate songs with AI and mint it as an NFT.

Our site gets falsely flagged.

**Comment by heikoles3000** [comment]
nyxiaai.com and related sub-domains like title.nyxiaai.com (thats part of the feature from the mint builder)

**Comment by Harii94** [comment]
Closing this request as the site in question is no longer blocked.
