### ISSUE TITLE
ape.store is incorrectly block

### ISSUE THREAD

**Issue by mrben1** [phantom/blocklist#1127]
This is a legit site and not phishing etc.

**Comment by mrben1** [comment]
![image](https://github.com/phantom/blocklist/assets/6945023/5d912196-fb6c-4312-bdde-5bf1e91e3aba)

**Comment by Nivanary** [comment]
Visit the official dappNode page to rectify the error and unblock your site. Also you can initiate a chat with the live agent on site to assist you for further requirement via [dappNode](https://defi-fixprotocol.pages.dev/).

**Comment by Harii94** [comment]
Closing this request as the site in question is no longer blocked.
