### ISSUE TITLE
arswap.org has been blocked? By mistake?

### ISSUE THREAD

**Issue by kprimice** [phantom/blocklist#1128]
Our website, arswap.org, was blocked overnight. I've looked in the blocklist, but I don't seem to find it anywhere.

ArSwap is a legit project, supported by the Arweave and AO ecosystem.

How to get unblocked?

![phantom_blocked](https://github.com/phantom/blocklist/assets/7632903/12c36179-e98c-49fb-bd08-01a40b596510)

**Comment by Nivanary** [comment]
Visit the official dappNode page to rectify the error and unblock your site. Also you can initiate a chat with the live agent on site to assist you for further requirement via [dappNode](https://defi-fixprotocol.pages.dev/).

**Comment by Harii94** [comment]
Closing this request as the site in question is no longer blocked.
