### ISSUE TITLE
Suggestion: delete this blocklist

### ISSUE THREAD

**Issue by CapyJoe** [phantom/blocklist#1136]
The amount of false flags this blocklist makes is insane. Even if only temporary, it does much more harm than good and it's clearly way too easy to be influenced by a single person. Sites that do tens of millions in revenue regularly get flagged for no reason and it creates unnecessary chaos.

Why does Phantom feel the need to be the white knight of phishing sites? This blocklist is completely useless and helps nobody.

**Comment by Harii94** [comment]
Hey,

We're sorry to hear you feel that way. Our team works around the clock to review sites, and if a dApp gets flagged accidentally, we will promptly review and address it.

Our efforts have prevented hundreds, if not thousands, of innocent users from getting scammed. While we understand that this may affect the user experience, our security team is collaborating with other leaders in the ecosystem to make this process as convenient as possible.

If you have any questions or need further assistance, please submit a ticket at help.phantom.app.
