### ISSUE TITLE
moobile.com.tr blocklist

### ISSUE THREAD

**Issue by emrcnakdmr** [phantom/blocklist#1137]
We are software development company in Turkiye called "Moobile". We also produce projects based NFT and Blockchain. Our customers who use your extension might confuse us as scammers. Please reconsider our blocklist decision. If you want more information about us please contact me via my e-mail: emrecan@moobile.com.tr
Regards.

**Comment by Harii94** [comment]
Hi,

Please forward these details to the Blowfish team for further investigation. You can reach them at: review@blowfish.xyz.
