### ISSUE TITLE
ladycoin.io has been blocked? By mistake?

### ISSUE THREAD

**Issue by Ladycoin2024** [phantom/blocklist#1141]
Our website, ladycoin.io, was blocked overnight. I've looked in the blocklist, but I don't seem to find it anywhere.

Ladycoin is pioneering the development of a global feminist community, dedicated to providing women with a supportive and empowering digital space. Our platform is more than just a cryptocurrency—it's a movement towards gender equality and female empowerment.

How to get unblocked this warning? Thanks.
![telegram-cloud-photo-size-5-6199281780331232236-y](https://github.com/phantom/blocklist/assets/169591714/8d13fcb3-e9ad-4847-be9f-a1604941703d)

**Comment by Harii94** [comment]
Hi,

Please forward these details to the Blowfish team for further investigation. You can reach them at: review@blowfish.xyz.
