### ISSUE TITLE
the website foxycoin.online was blocked but it is legitimate

### ISSUE THREAD

**Issue by Rafael-ba** [phantom/blocklist#1142]
the foxycoin.online website was blocked by phantom.. however I believe that this is an error in the algorithm.
foxycoin is the meme coin website I developed. It's a legitimate website for a legitimate meme coin. Through the ongoing pre-sale website, people can buy the token, and there is no malicious code on the website.
I request moderation to remove the site from the blocklist. Thank you in advance.

**Comment by Harii94** [comment]
Please send an email to review@blowfish.xyz for further investigation.
