### ISSUE TITLE
shibocle.com transaction blocked ? Mistake ?

### ISSUE THREAD

**Issue by Shibocle** [phantom/blocklist#1143]
Hello, I am creating a memecoin on solana, I was testing my site before publishing it. 
Since we're going to do an ICO I wanted to test if the site worked and I got this pop up. 
The site was blocked automatically by mistake. 
I'll have to fix that for the twitter marketing campaign.
awaiting your response, I send you my best regards, cordially

![Screenshot_phantom](https://github.com/phantom/blocklist/assets/169613417/a0a70678-a047-496d-afe7-bc60ea9c9865)

**Comment by Harii94** [comment]
Hi,

Please forward these details to the Blowfish team for further investigation. You can reach them at: review@blowfish.xyz.
