### ISSUE TITLE
All *.tech.blog domains are blocked, request to limit scope to specific bad subdomains

### ISSUE THREAD

**Issue by zants** [phantom/blocklist#1145]
tech.blog is used by WordPress to host websites/blogs, and users are able to make a subdomain on this.

Currently, all of tech.blog is blocked by Phantom, but it's likely the result of some bad actors on specific *.tech.blog subdomains.  This is preventing access to legitimate blogs/websites that chose tech.blog as their domain on WordPress.

**Comment by Harii94** [comment]
This is fixed.
