### ISSUE TITLE
nomis.cc website is blocked due to false positive

### ISSUE THREAD

**Issue by unchase** [phantom/blocklist#1150]
![image](https://github.com/phantom/blocklist/assets/29679226/bb3a9b3e-18ee-4c26-9990-ffa17bacd602)

Nomis is a multichain identity protocol that helps users build, manage, and leverage their onchain reputation and web3 projects to make onchain data-driven decisions.

Feel free to contact me by nick@nomis.cc

Best regards,
Nick, co-founder Nomis Protcol

**Comment by unchase** [comment]
Any updates?

**Comment by Harii94** [comment]
Closing this request as the site in question is no longer blocked.
