### ISSUE TITLE
Request to Unblock Website: False Positive Classification for Kiln.fi 

### ISSUE THREAD

**Issue by kilnmg** [phantom/blocklist#1153]
Hi Phantom Support Team,

I hope this message finds you well. I'm reaching out regarding the erroneous blocking of kiln.fi by Phantom's phishing protection system. 

It's a big blocking points for our users since it's impact all our applications and our public website: 
- retail dApp : stake.kiln.fi
- institutional portal : dashboard.kiln.fi
- public website : kiln.fi 

Hope we can resolve this issue soon and get in touch on the topic. 

Thanks,
Martin from Kiln's Product Team

**Comment by Harii94** [comment]
Closing this request as the site in question is no longer blocked.
