### ISSUE TITLE
degen.express false positive

### ISSUE THREAD

**Issue by AsparAugustus** [phantom/blocklist#1160]
Hi! We are a legitimate project and a token launchpad that allows users to create tokens without any initial liquidity, deploying them to our own DEX. Moreover we have been audited by Trust Security:
https://www.trust-security.xyz/degex-express-audit

Recently we have been under attack by malicious actors it seems.
We've been mass reported on Twitter by bots, and now ended up on a blocklist on Phantom?
Any help would be appreciated.

The following are links to our project:

twitter:
https://twitter.com/degenexpress69

main site:
https://degen.express/

docs:
https://docs.degen.express

Contact: https://x.com/0xThreeStigmata
TG: https://t.me/ThreeStigmata

**Comment by Harii94** [comment]
Hi,

Please forward these details to the Blowfish team for further investigation. You can reach them at: review@blowfish.xyz.
