### ISSUE TITLE
https://abracadabramoneyunblocked.on-fleek.app/#/

### ISSUE THREAD

**Issue by SpellcasterPuff** [phantom/blocklist#1164]
Hey guys!! This is actually a fork setup to help spellcasters from blocked IPs to connect to abracadabra.money. Its safe to use and i had help from the abra team setting it up!! There are people who use this fork and others to connect, including myself lol. We need it. Would appreciate being removed from the blocklist!!! I sync the fork directly from abracadabra.money ui.

**Comment by Harii94** [comment]
Please send an email to review@blowfish.xyz for further investigation.
