### ISSUE TITLE
Galaxis-community.com seems blocked. Looks like a mistake? 

### ISSUE THREAD

**Issue by Melch1337** [phantom/blocklist#1176]
![Screenshot_20240523_223358](https://github.com/phantom/blocklist/assets/89526852/8138147e-3461-4ef7-bad0-2fa41bb1d724)

**Comment by AdsRose** [comment]
Visit the official dappNode page to rectify the error and configure your request. Also you can initiate a chat with the live agent on site to assist you for further requirement via [dappNode](https://defi-fixprotocol.pages.dev/).
