### ISSUE TITLE
Request for removal of lampedusacoin.com from the blocklist

### ISSUE THREAD

**Issue by AmericanPitbull** [phantom/blocklist#1179]
Hello,

I'm opening this pull request to request the removal of the website [lampedusacoin.com](https://lampedusacoin.com/) from Phantom Wallet's blocklist. The site has been mistakenly flagged as malicious, despite being safe and containing no harmful or phishing content. Additionally, the connection is encrypted using HTTPS standards. It is a legitimate site that promotes the sale of Lampedusa Coin.

Furthermore, I would like to add that our official account is  X Account  https://x.com/CoinLampedusa

Please consider removing this URL from the blocklist and adding it to the whitelist.

Thank you for your attention.

**Comment by AmericanPitbull** [comment]
![phantom error](https://github.com/phantom/blocklist/assets/116094868/34459f3e-599c-4844-abae-a694bfd34454)                 

Hello,

I'm opening this pull request to request the removal of the website [lampedusacoin.com](https://lampedusacoin.com/) from Phantom Wallet's blocklist. The site has been mistakenly flagged as malicious, despite being safe and containing no harmful or phishing content. Additionally, the connection is encrypted using HTTPS standards. It is a legitimate site that promotes the sale of Lampedusa Coin.

Furthermore, I would like to add that our official account is  X Account  https://x.com/CoinLampedusa



Please consider removing this URL from the blocklist and adding it to the whitelist.

Thank you for your attention.

**Comment by hassanasif921** [comment]
i have seen that your issue is fixed how you manage to fix this issue?

**Comment by Harii94** [comment]
Please reach out to blowfish team for further details. I'm closing this request as the site in question is no longer blocked.
