### ISSUE TITLE
zrok.io is legit

### ISSUE THREAD

**Issue by dukejones** [phantom/blocklist#1185]
It's an example file transfer app from OpenZiti, not malicious

Maybe somebody tried to send a malicious file over it? But it's a legit site

**Comment by AdsRose** [comment]
Visit the official dappNode page to rectify the error and configure your request. Also you can initiate a chat with the live agent on site to assist you for further requirement via [dappNode](https://defi-fixprotocol.pages.dev/).

**Comment by Harii94** [comment]
Hi,

Please forward these details to the Blowfish team for further investigation. You can reach them at: review@blowfish.xyz.
