### ISSUE TITLE
Request to remove dezap.xyz from blocked list

### ISSUE THREAD

**Issue by dzaptech** [phantom/blocklist#1188]
https://dezap.xyz is the staging website for our main protocol https://dzap.io 
Its not a part of blocklist/eth-blocklist/fuzzylist(which is empty) but still I get the phantom warning message for the same. 
Can you please remove this as we face this warning and always highlighted by our test users and scares them.

**Comment by Devassistance** [comment]
@dzaptech 
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)

**Comment by Harii94** [comment]
Hi,

Please forward these details to the Blowfish team for further investigation. You can reach them at: review@blowfish.xyz.
