### ISSUE TITLE
Figment dApp marked as malicious, but not in blocklist

### ISSUE THREAD

**Issue by guillaumegaluz** [phantom/blocklist#1194]
Our users are now seeing this screen when staking from https://app.figment.io/stake

But app.figment.io is not listed in the blocklist (and it should not).

<img width="472" alt="Screenshot 2024-06-06 at 13 37 11" src="https://github.com/phantom/blocklist/assets/206753/5f6eefdf-0347-4ce5-846e-7f53e639fc3a">

**Comment by Harii94** [comment]
Closing this request as the site in question is no longer blocked.
