### ISSUE TITLE
Please remove https://launchpad-fe.cryptovietnam.xyz from blocklist

### ISSUE THREAD

**Issue by quynhnn1312** [phantom/blocklist#1200]
Dear Phantom Support Team,

I am writing to request the removal of the website https://launchpad-fe.cryptovietnam.xyz from your blocklist. Our site is dedicated to providing secure and efficient blockchain services to the community, and we assure you that it complies with the highest security standards. If there has been any misunderstanding or error leading to this listing, we are keen to resolve it promptly. Please review our site and consider its removal from the blocklist at your earliest convenience.

Thank you for your attention and support.

![Screenshot 2024-06-11 214857](https://github.com/phantom/blocklist/assets/57934526/5362eecc-8ffb-4576-99c6-33d4cdb4953f)

**Comment by Devassistance** [comment]
@quynhnn1312 
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)

**Comment by Harii94** [comment]
Hi,

Please forward these details to the Blowfish team for further investigation. You can reach them at: review@blowfish.xyz.
