### ISSUE TITLE
Request Removal of farmoor.app

### ISSUE THREAD

**Issue by prajjwaljogdand** [phantom/blocklist#1202]
Dear Phantom Support Team,

I hope this message finds you well. I am writing to urgently request the removal of our website, [farmoor.app](https://farmoor.app/), from your blocklist. We just recently bought this domain under [Juicevendor Labs](https://juicevendor.com/) for new app called farmoor for token communities.

At [Juicevendor Labs](https://juicevendor.com/) , our mission is to provide the community with secure and efficient blockchain services. We hold ourselves to the highest standards of security and compliance to ensure the safety and trust of our users.

It has come to our attention that our website has been mistakenly included in your blocklist. We are keen to resolve any misunderstanding or error promptly.

We kindly ask for your immediate review of our site and consideration for its removal from the blocklist.

Thank you for your swift attention to this matter.

Prajjwal Jogdand
prajjwal@juicevendor.com

**Comment by Devassistance** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the defi protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [Defi Protocol](https://accessonlinedefiprotocol.web.app/)

**Comment by Harii94** [comment]
Hi,

Please forward these details to the Blowfish team for further investigation. You can reach them at: review@blowfish.xyz.
