### ISSUE TITLE
Phishing Drainer site

### ISSUE THREAD

**Issue by stopscamdapp** [phantom/blocklist#1212]
cleandirectys.com
dapprrader.com
dapplisted.org
airsolutionhub.com
dropclamify.com
dprddr.com
dprddr.in
dprddr.org
dapdirects.org
dapdirects.net
dapdirects.com
appridects.org
dappnraidar.net
dappnraidar.org
dappnradars.net
dappnradars.org
appdirecting.com
mdm-fasp.com
dappradar.wiki
dappadar.investments

**Comment by Harii94** [comment]
Thanks for reporting. We will review them and add them to our blocklist via Blowfish.
