### ISSUE TITLE
Request to remove qonstant.fi from the blocklist

### ISSUE THREAD

**Issue by dhruvio** [phantom/blocklist#1214]
**Please remove qonstant.fi from this blocklist.**

I am the project's founder, feel free to ask me any questions.

Qonstant has been live since 2023. Our smart contracts are fully audited by Halborn, and we do not take custody of customer funds (everything is fully settled on-chain).

Qonstant App: https://qonstant.fi
Qonstant Whitepaper/Docs: https://docs.qonstant.fi
X Qoda Finance: https://x.com/QodaFinance
X Qonstant: https://x.com/QonstantApp

**Comment by Harii94** [comment]
Hi, please forward these details to Blowfish team to investigate further.You can contact them at: review@blowfish.xyz.
