### ISSUE TITLE
blocklist removal StreamNFT

### ISSUE THREAD

**Issue by piyush-chittara** [phantom/blocklist#1219]
https://streamnft-utility.vercel.app/

This is testing env of our blockchain NFT app
following is our security audit if it helps: https://docs.streamnft.tech/introduction/security-audit

please find unblocked metamask issue for the same:
https://github.com/MetaMask/eth-phishing-detect/issues/65643

**Comment by Harii94** [comment]
Hi, please forward these details to Blowfish team via email to investigate further. You can contact them at review@blowfish.xyz
