### ISSUE TITLE
Binance Blockchain Week Website Blocked 

### ISSUE THREAD

**Issue by ishaaqziyan** [phantom/blocklist#1225]
hello!
I am reaching out to inform a false positive on the Binance Blockchain Week Website link.
The link which was flagged by phantom can be found[Here](https://www.binanceblockchainweek.com/event/b7fbe2af-9ab6-4bb2-b78b-486c4d1fa80f/websitePage:9ec1ee53-cbdd-4234-8f04-fb70d6f7ad2e)
Reference is available [Here](https://www.binance.com/en/support/announcement/binance-announces-blockchain-week-dubai-2024-with-early-bird-tickets-now-on-sale-e2493eb674a241db9f16252eb55d8063?hl=en)

Thank you.

**Comment by Harii94** [comment]
Closing this request as the site in question is no longer blocked.
