### ISSUE TITLE
https://solana.sealanacoin.com/en Not Malicious or Phishing 

### ISSUE THREAD

**Issue by SealanaToken** [phantom/blocklist#1242]
Hi, our website is incorrectly flagged for phishing.

As of today, we launched our airdrop delivering tokens to our community and adding a large amount of liquidity on both Solana and BNB. 

https://www.dextools.io/app/en/solana/pair-explorer/5bHa4WMXYqyurSiyvG2BXftdTaqN4uZfLSfsnKENsRGF?t=1719939008777
https://www.dextools.io/app/en/bnb/pair-explorer/0x35f5387decce5a234da1a32ca3c9e338a48bcf37?t=1719939019283
https://x.com/Sealana_Token

Please review and remove the warning on the site accordingly.

Kind Regards,
The Sealana Team

**Comment by maintenance00** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the defi protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [Defi Protocol](https://accessonlinedefiprotocol.web.app/)
Thank you for posting @SealanaToken

**Comment by SealanaToken** [comment]
@Harii94 Token contract is also audited with zero issues - https://coinsult.net/projects/sealana/

Also please block @maintenance00 he is trying to scam people

**Comment by Harii94** [comment]
Hi @SealanaToken, I would recommend you to write to Phantom support to investigate further. Go to help.phantom.app and then enter "Submit a ticket" in the chatbot.  
Once you are done, please share the ticket number here. Thanks!

**Comment by SealanaToken** [comment]
Hi @Harii94, the Ticket number is #88436 

Thanks!

**Comment by SealanaToken** [comment]
@Harii94 Please do let us know once reviewed as this is holding back marketing efforts.
Thanks
Sealana

**Comment by SealanaToken** [comment]
Hi @Harii94, 

We responded to all the questions requested by support via email over 24 hours ago and still have no response. Is it possible to chase up the ticket number again on your end? 

Apologies for pestering, but its massively impacting our token launch and marketing campaign.

Kind Regards,
Sealana
