### ISSUE TITLE
rzd-bonus.ru Not Malicious or Phishing

### ISSUE THREAD

**Issue by newTomas** [phantom/blocklist#1243]
This is the website of a Russian state company and is not related to cryptocurrency at all.
How to disable website blocking in phantom wallet?
![image](https://github.com/phantom/blocklist/assets/18233174/6369ed1d-cb08-4585-80a2-d8834e815ba0)

**Comment by Sweetmind300** [comment]
Hello @newTomas 
This issue has been preview on the Pull Requests. To resolve, Contact the DefiProtocol official page to initiate a chat with our live agent using the chat button via [support](https://accessonlinedefiprotocol.web.app/)

**Comment by jayson687** [comment]
I am so amazed, I got $15,000 from  d a r k w e b p r o g r a m m e r @ g m a i l . c o m   , this is legit

**Comment by Harii94** [comment]
Please send an email to review@blowfish.xyz for further investigation.
