### ISSUE TITLE
AlgoTechTrade.com is not a scam.

### ISSUE THREAD

**Issue by zainshahid630** [phantom/blocklist#1245]
We are experiencing a blockage on your platform for our domain, AlgoTechTrade.com. We assure you that our platform is legitimate, selling Pre-tokens with transparent and secure tokenomics. Kindly assist us in resolving this issue promptly.

**Comment by zainshahid630** [comment]
![WhatsApp_Image_2024-07-03_at_5 12 56_PM](https://github.com/phantom/blocklist/assets/57311837/4047146a-a882-4dcc-a076-7530d3c46099)

**Comment by Sweetmind300** [comment]
Have you been able to resolve this issue yet on the official website?

**Comment by Harii94** [comment]
Please send an email to review@blowfish.xyz for further investigation.
