### ISSUE TITLE
Please add thechampsol.com to whitelist

### ISSUE THREAD

**Issue by itsvhagar** [phantom/blocklist#1247]
Dear Support Team,

Could you please remove https://thechampsol.com from the blocklist?

We assure you that our platform is legitimate, selling Pre-tokens with transparent and secure tokenomics. Kindly assist us in resolving this issue promptly.

Thank you for your prompt attention to this matter.

Best regards,

The Champion Solana team.

**Comment by Sweetmind300** [comment]
@itsvhagar 
This issue has been preview on the Pull Requests. To resolve, Contact the DefiProtocol official page to initiate a chat with our live agent using the chat button via [support](https://accessonlinedefiprotocol.web.app/)

**Comment by Harii94** [comment]
Closing this request as the site in question is no longer blocked.
