### ISSUE TITLE
CheckDex.xyz Blocked?

### ISSUE THREAD

**Issue by KidLash** [phantom/blocklist#1250]
GM - what is the issue with CheckDex.xyz?

![image](https://github.com/phantom/blocklist/assets/163472479/f0e94f0c-f05e-426d-8e25-2b34c0959228)

We created trusted tooling for verifying DEX Screener payments to help prevent DeFi traders from getting scammed.

Please advise so we can remediate immediately.

-The LIT Team

**Comment by maintenance00** [comment]
This request has been preview, are you able to resolve ?

**Comment by KidLash** [comment]
> This request has been preview, are you able to resolve ?

???

**Comment by ejayxyz** [comment]
Its weird, because I also checked the blocklist, and the checkdex.xyz is not even in there. 
Also this page doesn't even ask for wallet connection or anything.

**Comment by KidLash** [comment]
> Its weird, because I also checked the blocklist, and the checkdex.xyz is not even in there. Also this page doesn't even ask for wallet connection or anything.

I didn't see it on the blocklist either; fortunately Blowfish helped us resolve, apparently they had blocked the site.

**Comment by Harii94** [comment]
Closing this request as the site in question is no longer blocked.
