### ISSUE TITLE
Legit CC website on blocklick

### ISSUE THREAD

**Issue by nheingit** [phantom/blocklist#1254]
https://milestone.myfinanceservice.com/ is a mastercard / creditcard service that's blocked by Phantom for some reason. No way to connect your wallet or do anything crypto related on there.

**Comment by dhadx** [comment]
> https://milestone.myfinanceservice.com/ is a mastercard / creditcard service that's blocked by Phantom for some reason. No way to connect your wallet or do anything crypto related on there.

Phantom block your Mastercard from purchasing crypto ??

**Comment by Harii94** [comment]
Hey @nheingit, This is now unblocked. 

Sorry for the delay in response!
