### ISSUE TITLE
My Website isnt phishing! Kindly add it to the whitelist

### ISSUE THREAD

**Issue by oshergluck** [phantom/blocklist#1255]
My website marked as phishing because of another website with a partialy similar url.
Kindly add my website to the whitelist.
https://www.ultimatedeal.net

**Comment by GTHubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
Thank you for posting @oshergluck

**Comment by GTHubDevi** [comment]
Are you able to resolve ?
