### ISSUE TITLE
Code SDK for developers blocked by Phantom

### ISSUE THREAD

**Issue by Yiwen-Gao** [phantom/blocklist#1260]
I'm confused why Code's developer docs (https://code-payments.github.io/code-sdk/docs/guide/introduction.html) are blocked by Phantom. I don't see an entry for `code-payments.github.io` in `blocklist.yaml`.

The developer docs are linked at the bottom of Code's main website (https://getcode.com/), and they only contain documentation, so it seems like a red herring here.

Thanks!

**Comment by Harii94** [comment]
Hey, the site is present in multiple blocklists like seal, metamask, etc. I request you to send an email to review@blowfish.xyz for further investigation.
