### ISSUE TITLE
Remove Bando.cool from blocklist.

### ISSUE THREAD

**Issue by luisgj** [phantom/blocklist#1276]
Hi. We are not a malicious site. Why would you block us? 

Also I don't find my site in the master branch. but it is blocked nonetheless.

Please remove it.

<img width="870" alt="Screenshot 2024-08-05 at 7 44 57 p m" src="https://github.com/user-attachments/assets/dce6e995-7a3d-4f5d-a884-05f433b349a8">

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the dAppNode page to rectify this error with the Ticket ID USD5562, Also you can initiate a chat with the live agent on the chat button to get more information about your request via [Support Page](https://defi-fixprotocol.pages.dev/)
Regards.

**Comment by Harii94** [comment]
Closing this request as the site in question is no longer blocked.
