### ISSUE TITLE
Remove blindpay.com from blocklist

### ISSUE THREAD

**Issue by BernardoSM** [phantom/blocklist#1277]
BlindPay is a fully regulated company in the US so please let us know what you need to remove our domain from the blocklist.

![CleanShot 2024-08-07 at 13 36 47](https://github.com/user-attachments/assets/f0344f26-cec2-4851-b8f7-6a1ac455be48)

I also added a PR to add blindpay on the whitelist: https://github.com/phantom/blocklist/pull/1274

Thank you!

**Comment by Harii94** [comment]
Closing this request as the site in question is no longer blocked.
