### ISSUE TITLE
Request to Whitelist testnet.ernscan.io as a Non-Malicious Site

### ISSUE THREAD

**Issue by 1xAhmed** [phantom/blocklist#1280]
I am a member of the Ethernity project team. We have recently launched our testnet and are about to launch our mainnet. However, some of our users are experiencing issues accessing our testnet via the Phantom Wallet. The domain testnet.ernscan.io is being flagged as malicious, which is incorrect.

Could you please investigate and remove testnet.ernscan.io from your malicious site database? Our URL is secure and poses no threat to users. For added convenience, we request that you also add this URL to your whitelist documentation.

URL: testnet.ernscan.io
![Image](https://github.com/user-attachments/assets/ba21540c-0938-44df-95ce-ae6bbc7daf13)

Thank you for your assistance.

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
@1xAhmed 
Regards

**Comment by samg95-jpg** [comment]
Closing this request as the site in question is no longer blocked.
