### ISSUE TITLE
PLease unblock Shillstack.com

### ISSUE THREAD

**Issue by ThisNewMark** [phantom/blocklist#1289]
Hello, Shillstack.com is blocked. It creates custom gifs and telegram stickers by simply pasting in a coins contract address. 

We added Helio pay for crypto payments and Phantom is now blocking shillstack.com

Could you please add Shillstack.com to the whitelist ASAP?

Thank you!

**Comment by ThisNewMark** [comment]
Pull request #1290 to add shillstack to the whitelist.

**Comment by samg95-jpg** [comment]
Closing this request as the site in question is no longer blocked.
