### ISSUE TITLE
Please unblock starknet.quest

### ISSUE THREAD

**Issue by fricoben** [phantom/blocklist#1299]
Starknet quest is a quest platform for Starknet and is not trying to impersonate the Starknet foundation in any way

https://starknet.quest/

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the defi protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [Defi Protocol](https://accessonlinedefiprotocol.web.app/)
@fricoben 
Best Regards

**Comment by samg95-jpg** [comment]
Closing this request as the site in question is no longer blocked.
