### ISSUE TITLE
Please unblock zir.exchange

### ISSUE THREAD

**Issue by laashad** [phantom/blocklist#1301]
Our domain is https://zir.exchange/.

Dear Phantom team,

Today, we have resolved many misunderstandings:
MetaMask has unblocked our domain: https://github.com/MetaMask/eth-phishing-detect/issues/76922
Chain Patrol has unblocked our domain and set the status to allowed: https://app.chainpatrol.io/search?content=zir.exchange

There is no proof that our domain engages in any malicious activities. As we host ongoing events, being flagged as a malicious site by Phantom is causing negative effects on our projects and community.

We kindly and urgently request the removal of our domain from being flagged by Phantom.

Thank you for your time!

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the defi protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [Defi Protocol](https://accessonlinedefiprotocol.web.app/)
Best Regards @laashad

**Comment by laashad** [comment]
Please unblock the domain: zir.exchange

We will provide any information you need. Thank you!
