### ISSUE TITLE
Unblock Defi-g.com

### ISSUE THREAD

**Issue by Americano00** [phantom/blocklist#1302]
please unblock defi-g.com

i own the website.

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the defi protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [Defi Protocol](https://accessonlinedefiprotocol.web.app/)
@Americano00 
Best Regards.

**Comment by Americano00** [comment]
help please

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.
