### ISSUE TITLE
Please unblock gmgn.ai

### ISSUE THREAD

**Issue by BlackKeyZ** [phantom/blocklist#1303]
Hello, we are the dev team of gmgn.
The website is gmgn.ai
Twitter is https://x.com/gmgnai
It's a meme defi trading tool.

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the defi protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [Defi Protocol](https://accessonlinedefiprotocol.web.app/)
@BlackKeyZ 
Best Regards

**Comment by samg95-jpg** [comment]
Closing this request as the site in question is no longer blocked.
