### ISSUE TITLE
Please unblock KelpDAO docs page

### ISSUE THREAD

**Issue by shilpi1958** [phantom/blocklist#1305]
This is the product team of KelpDAO

please help unblock our docs 
https://kelp.gitbook.io/kelp/kelp-gain/airdrop-gain

website : https://kelpdao.xyz/gain/airdrop-gain/
Twitter : https://x.com/KelpDAO

**Comment by shilpi1958** [comment]
@steveluscher @raulriera @lexer 

hey team, please help unblock us

**Comment by samg95-jpg** [comment]
Closing this request as the site in question is no longer blocked.
