### ISSUE TITLE
Please whitelist notcoin.website

### ISSUE THREAD

**Issue by thisisgold** [phantom/blocklist#1307]
Someone has marked the site notcoin.website as phishing, but this is a mistake. Please add it to the whitelist.

**Comment by QuimbyJr** [comment]
Hello @thisisgold 
This issue has been preview on the Pull Requests. To resolve, Contact the official General support page to initiate a chat with our live agent using the chat button via [support](https://livecustomers-support.web.app)

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.
