### ISSUE TITLE
Blocking fanlink.tv

### ISSUE THREAD

**Issue by cipherkilledit** [phantom/blocklist#1313]
Please remove this domain (fanlink.tv) from your list of prohibited sites. Phantom is now blocking fanlink.tv, which is similar to Linktree but for musicians. 

Example url: https://cipher.fanlink.tv/social

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.

**Comment by cipherkilledit** [comment]
Really? You couldn't just forward this to them? The error itself says to report this here. You need to fix the error message if you don't want people reporting this here.

**Comment by sheridanwendt** [comment]
@samg95-jpg, ironically blowfish is asking that you email them 

![blowfish](https://github.com/user-attachments/assets/4d466fb6-5318-4607-b22c-d8fb7249c5cf)
![image](https://github.com/user-attachments/assets/dea3fbd0-611d-43bf-9565-83acd29e4b89)

**Comment by cipherkilledit** [comment]
They told me<https://github.com/phantom/blocklist/issues/1313> to reach out to you.

Stay Smart,
Team Cipher
720-767-2008
Listen <https://cipher.fanlink.to/music> | Connect<https://cipher.fanlink.to/social>
CipherMusic.com<http://ciphermusic.com/>
Cipher Entertainment
________________________________
