### ISSUE TITLE
Re-request to unblock domain: zir.exchange

### ISSUE THREAD

**Issue by laashad** [phantom/blocklist#1315]
Dear Support Team,

Could you please unblock the domain: https://zir.exchange ?
We haven't participated in any malicious activity or phishing. We are not being blocked by eth-phishing-detect or PhishFort 
Our project is an NFT marketplace on the Zircuit network, which Phantom doesn't support at the moment, and it is being flagged as a malicious website on Phantom.
In the meantime, we have provided all the necessary information to Blowfish, along with a developer's vouch for us, but we still haven't received any response.

This issue is significantly impacting our operations. Kindly review our request. If it is declined, please let us know the reason.

Thank you for your prompt attention to this matter!

**Comment by nguyenphuminh** [comment]
Hey guys, I confirm that I vouch for the zir.exchange team. Ticket 2451. Thank you!
