### ISSUE TITLE
mineprobusiness.net domain warning

### ISSUE THREAD

**Issue by MineProGitHub** [phantom/blocklist#1317]
Hello - I'm from the MinePro team and Phantom appears to be issuing a warning to our domain (mineprobusiness.net)
![photo_2024-08-15_23-59-15](https://github.com/user-attachments/assets/9db2ce59-ba3b-4d68-9274-1a9e1e589169)

Please remove it - or let me know if there is anything we need to do/prove on our end to have it removed (prove we're not a scam, etc.)

Thanks a lot

**Comment by ACCmaintenance** [comment]
This issue has been previewed on Pull Request. To Resolve,
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@MineProGitHub

**Comment by MineProGitHub** [comment]
Hello, is this a scam website? I'm not sure what you're linking me to with this support page, can you prove you are an admin?

**Comment by MineProGitHub** [comment]
Any news?

**Comment by MineProGitHub** [comment]
Please fix it, thank you

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.
