### ISSUE TITLE
Request to Whitelist zkstack.io - Official zkSync L2 Platform

### ISSUE THREAD

**Issue by dindonero** [phantom/blocklist#1321]
**Description:**

I would like to request that the Phantom Wallet team consider whitelisting the domain `zkstack.io`. This website is part of the zkSync ecosystem and serves as an official platform for launching custom Layer 2 (L2) solutions on Ethereum.

### Background:

`zkstack.io` is a newly launched initiative by the zkSync team, aiming to provide a framework for developers to deploy their own Layer 2 scaling solutions. As the adoption of zkSync grows within the Ethereum community, integrating support for `zkstack.io` within Phantom Wallet would greatly benefit users who are involved in the zkSync ecosystem.

### Reason for Request:

- **Official zkSync Project:** The domain is part of the zkSync ecosystem, which has gained significant traction as a leading solution for Ethereum Layer 2 scaling.
- **Security and Trust:** Whitelisting `zkstack.io` will help prevent phishing attempts and provide users with confidence when interacting with the platform through Phantom Wallet.
- **Increased Utility:** Supporting `zkstack.io` aligns with Phantom Wallet’s goal of facilitating safe and easy access to decentralized applications (dApps) and Layer 2 solutions.

### Impact:

Whitelisting `zkstack.io` will enhance user experience and security, allowing Phantom Wallet users to seamlessly interact with the zkSync ecosystem and its new L2 launch platform.

### Suggested Action:

Please review and consider adding `zkstack.io` to the list of whitelisted domains in Phantom Wallet.

Thank you for your time and consideration.

**Comment by samg95-jpg** [comment]
Closing this request as the site in question is no longer blocked.
