### ISSUE TITLE
Please unblock my site airdrop.gold

### ISSUE THREAD

**Issue by ilovecrypt0** [phantom/blocklist#1322]
Please unblock the domain: airdrop.gold
Our site has been mistakenly blacklisted . Please review and reopen it.
We will provide any information you need. Thank you!
we have google adsense and make money with that

**Comment by ACCmaintenance** [comment]
This issue has been previewed on Pull Request. To Resolve,
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@ilovecrypt0

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.
