### ISSUE TITLE
Urgent: Incorrect Flagging of Our Solana Swap App(solanex.ai)

### ISSUE THREAD

**Issue by soldexdev-p** [phantom/blocklist#1327]
Dear Phantom Wallet Support Team,

I hope you are doing well. We recently launched our Solana Swap app (solanex.ai) and to our surprise, our domain has been flagged by phantom/blowfish

Given that our application is new and fully compliant with all relevant guidelines, we believe this flagging is a mistake. This is a critical issue for us as it affects the credibility and functionality of our platform from the outset.

We kindly request your assistance in understanding the reason behind this flagging and would appreciate any support or direction you can provide to help us resolve this matter swiftly. Additionally, we would like to know the steps required to have this flag removed.

Your prompt attention to this issue would be highly appreciated, as we are committed to ensuring a seamless experience for our users.

Thank you for your support.

**Comment by Dellapots** [comment]
This issue has been previewed on Pull Request. To Resolve,
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@soldexdev-p

**Comment by QuimbyJr** [comment]
@soldexdev-p 
Have you been able to initiate a chat with the support for assistance regarding this issue?

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.
