### ISSUE TITLE
Remove solana-suite.org from blocklist

### ISSUE THREAD

**Issue by fukaoi** [phantom/blocklist#1328]
Dear Blowfish Team,

* Blowfish ticket number:  2630 
* my domain: solana-suite.org

Please remove my domain from the block list.

**Comment by Dellapots** [comment]
This issue has been previewed on Pull Request. To Resolve,
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@fukaoi

**Comment by fukaoi** [comment]
Hi @Dellapots 

I received the following message from Blowfish Support, which is why I created the issue. Is this not appropriate?

> For verification purposes, please have fukaoi > on GitHub create anything with ticket number > 2630 and the domain you'd like to have cleared.

**Comment by fukaoi** [comment]
Thank you Blowfish team!
my problem is solved
