### ISSUE TITLE
PLEASE UNBLOCK DEFI-G.COM

### ISSUE THREAD

**Issue by Americano00** [phantom/blocklist#1329]
We are about to launch on solana and we can not have our website marked suspicious. Thank you in advanced

**Comment by Dellapots** [comment]
This issue has been previewed on Pull Request. To Resolve,
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@Americano00

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.
