### ISSUE TITLE
Unblock mim-lab.lol ticket 2341

### ISSUE THREAD

**Issue by blump** [phantom/blocklist#1330]
Hey,

After our e-mail exchanges. I open this issue for the domain mim-lab.lol and the subdomain MRM.mim-lab.lol
Ticket number 2341 

Thank you for your interest.

**Comment by blump** [comment]
Hello,
Someone to validate my request?
All information has been communicated by mail during numerous exchanges.

Kind regards,

**Comment by blump** [comment]
Hello,

Someone to unlock mim-lab.lol and its subdomains ... ?

**Comment by samg95-jpg** [comment]
Closing this request as the site in question is no longer blocked.
