### ISSUE TITLE
Please unblock marketplace.investmentx.com

### ISSUE THREAD

**Issue by madsjehg** [phantom/blocklist#1332]
We're a serious platform aiming to fractionalize luxury real-world assets.

This is our X page: https://x.com/InvestmentX_

This platform is an extension of the already existing business called 'Investment Watches'. You can find our page here: https://www.investmentwatches.com/

If you need any other information, please let me me know.

**Comment by samg95-jpg** [comment]
Closing this request as the site in question is no longer blocked.
