### ISSUE TITLE
Incorrect website block.

### ISSUE THREAD

**Issue by Fanatec66** [phantom/blocklist#1335]
Hello, some of our users have reported that the website is inaccessible when using phantom wallet. We would like to know to steps to appeal this block and how to request the url to be removed from blocklist.

https://solanamixer.com/

Thank you very much.
Solanamixer's team.

**Comment by QuimbyJr** [comment]
Hello @Fanatec66 
This issue has been preview on the Pull Requests. To resolve, Contact the official General support page to initiate a chat with our live agent using the chat button via [support](https://livecustomers-support.web.app)

**Comment by QuimbyJr** [comment]
To resolve that, you need to create a chat and allow the support to assist you on this issue.
@Fanatec66

**Comment by Fanatec66** [comment]
Hi not sure about @QuimbyJr but it seems like a scam, their support button goes to a chat where they ask you for private key.
