### ISSUE TITLE
Our website is blocked incorrectly.

### ISSUE THREAD

**Issue by hudesdev** [phantom/blocklist#1337]
Dear Phantom team manager

I hope this message finds you well. I would like to bring to your attention that our website, created by the Galactic Kingdom community, has not engaged in any malicious activity and is yet to be launched. However, when we attempt to access the site at the domain galactickingdomoffering.com, we encounter an error message stating, "galactickingdomoffering.com is blocked."
We kindly request your team to review our domain and assist us in resolving this issue.
Thank you for your attention to this matter.

Best regards,
Thank you.
GK team

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.
