### ISSUE TITLE
Request to Unblock Our Game at DegenFun.com

### ISSUE THREAD

**Issue by davedev83** [phantom/blocklist#1344]
Please review and unblock our game at DegenFun.com. The site is not malicious in any way.

Our game operates on a provably fair system with a 50/50 chance, utilizing the verifiable random generator from random.org to ensure transparency, which our players can independently verify. We charge only a small platform fee and do not profit from wins or losses. Players send their wagers to a PDA and are the only ones authorized to withdraw from it.

We would greatly appreciate it if you could unblock the site at your earliest convenience. We have previously developed and whitelisted games with Blowfish, and this is our third Solana-based game.

Thank you for your attention to this matter.

Best regards,
David

**Comment by summerly01** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)

**Comment by davedev83** [comment]
Phantom admins, the comment from summerly01 looks like spam and the link might be dangerous. 

Also, please unblock our domain. We're working really hard on our dapp and would appreciate a speedy response.

**Comment by davedev83** [comment]
Can we please get an update on this?
