### ISSUE TITLE
Please unblock our website

### ISSUE THREAD

**Issue by sofialovesyourtesting** [phantom/blocklist#1349]
Our token presale website https://presale.grannyhoney.com/ has mistakenly been flagged by phantom wallet. 
Please help us and solve the issue.

**Comment by laalauren1** [comment]
> Our token presale website https://presale.grannyhoney.com/ has mistakenly been flagged by phantom wallet. Please help us and solve the issue.

@sofialovesyourtesting  It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID PHA07638
Please see the link below to our dedicated support line:
[phantom live support](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by summerly01** [comment]
This issue has been previewed on Pull Request. To Resolve,
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@sofialovesyourtesting

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.
