### ISSUE TITLE
Please unblock our website

### ISSUE THREAD

**Issue by hazalgumus** [phantom/blocklist#1351]
Please help us resolve the issue with our website https://bulksendersolana.vercel.app/ being mistakenly flagged by Phantom Wallet.

**Comment by laalauren1** [comment]
> Please help us resolve the issue with our website https://bulksendersolana.vercel.app/ being mistakenly flagged by Phantom Wallet.

It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID PHA07638
Please see the link below to our dedicated support line:
[Phantom Network DApps Support Ticket Requests](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Cognacy** [comment]
This issue has been previewed on Pull Request. To Resolve,
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@hazalgumus

**Comment by summerly01** [comment]
This issue has been previewed on Pull Request. To Resolve,
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@hazalgumus

**Comment by samg95-jpg** [comment]
Closing this request as the site in question is no longer blocked.

**Comment by hazalgumus** [comment]
https://prnt.sc/z1rpAr0Onpsa

The problem still persists..
