### ISSUE TITLE
Please unblock our website

### ISSUE THREAD

**Issue by hazalgumus** [phantom/blocklist#1352]
Please help us resolve the issue with our website https://bulksendersolana.vercel.app/ being mistakenly flagged by Phantom Wallet.

https://prnt.sc/z1rpAr0Onpsa

The problem still persists..

https://github.com/phantom/blocklist/issues/1351#issuecomment-2341314329

**Comment by summerly01** [comment]
This issue has been previewed on Pull Request. To Resolve,
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@hazalgumus

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.
