### ISSUE TITLE
[Legitimate Site Blocked] syncswap.dappos.com

### ISSUE THREAD

**Issue by Jiangyj19** [phantom/blocklist#1354]
Dear MetaMask team, 

We are reaching out as we believe that https://syncswap.dappos.com by dappOS and SyncSwap is being mistakenly identified.

Please kindly check this tweet for the collaboration between dappOS and SyncSwap : https://x.com/syncswap/status/1820908107427651684

Also our audit reports : https://dappos.gitbook.io/docs/dappos/security/external-audits

Appreciate your kind help!!

**Comment by Jiangyj19** [comment]
![15831726225966_ pic](https://github.com/user-attachments/assets/67db2aa4-db38-4971-a98f-c9da1d78d02e)
![15841726225979_ pic](https://github.com/user-attachments/assets/5cb350b7-8a4c-4d5c-9e9e-f5156340f7bb)

**Comment by summerly01** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@Jiangyj19
