### ISSUE TITLE
Site blocked, not on block list: dscvrbl.ink

### ISSUE THREAD

**Issue by rckprtr** [phantom/blocklist#1355]
This site is used as a wrapper around Blinks for DSCVR (https://dscvr.one/) and is blocked

Site: https://www.dscvrbl.ink/?action=https://jupiter.dial.to/swap/SOL-Bonk

I tried to find it in the block list but could not.

Thank you!
Rick

**Comment by summerly01** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@rckprtr
