### ISSUE TITLE
ZKML dApp flagged as a phishing site

### ISSUE THREAD

**Issue by ZkReson** [phantom/blocklist#1356]
Hello, 

Im ZkReson, product lead at ZKML =>  https://www.zkml.systems/
We don't know why but https://zwap.systems is being flagged as a phishing site while its def not
Can y'all fix this asap please ?

Thanks

The ZKML Team

**Comment by summerly01** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@ZkReson

**Comment by QuimbyJr** [comment]
Hello @ZkReson 
Have you been able to resolve your issue yet?

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.
