### ISSUE TITLE
celestia.cool flagged as phishing site, but it is a mempool visualizer I built for Celestia

### ISSUE THREAD

**Issue by jcstein** [phantom/blocklist#1359]
Source: https://github.com/jcstein/celestia-cool

I tried to find it on main at 5bbaa12 but it is not in the list...please help resolve! thanks
<img width="1542" alt="Screenshot 2024-09-16 at 11 26 20 AM" src="https://github.com/user-attachments/assets/d97ab0e4-0dca-420c-8f94-ab598bf0c48b">

<img width="1542" alt="Screenshot 2024-09-16 at 11 29 04 AM" src="https://github.com/user-attachments/assets/aec424d9-a2be-46e4-b142-369465f29297">
<img width="1542" alt="Screenshot 2024-09-16 at 11 29 12 AM" src="https://github.com/user-attachments/assets/5ddcf669-406a-45f2-ad1e-4d01e3c2f543">

There is even a note and link on the site to the source...

<img width="655" alt="Screenshot 2024-09-16 at 11 29 28 AM" src="https://github.com/user-attachments/assets/529cb6b3-4a79-4f1c-bb12-29b7acafb0d6">

**Comment by jcstein** [comment]
had someone do the same thing on metamask too smh

https://github.com/MetaMask/eth-phishing-detect/pull/14813

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.

**Comment by jcstein** [comment]
really? i linked the open source code and it's literally a static site... seems like overkill to have to email too. what's the point of making an issue if this is what happens?

this is not completed.

**Comment by woodydeck** [comment]
> Please send an email to [review@blowfish.xyz](mailto:review@blowfish.xyz) for further investigation.

This is a totally unacceptable reply and your feet need to be held to the fire. You can't outsource to a company and not take responsibility. They don't reply or help. It's pointless to email them.

**Comment by jcstein** [comment]
please have them respond ASAP @samg95-jpg
