### ISSUE TITLE
chainlinklabs.com is incorrectly blocked

### ISSUE THREAD

**Issue by bradford-m** [phantom/blocklist#1361]
chainlinklabs.com is the official careers website of [Chainlink Labs](https://x.com/chainlinklabs?lang=en) and should not be blocked. I couldn't find any references to chainlinklabs.com in any of the blocklists, so not sure why this is happening 🤔 

Steps to reproduce:

1. Have the latest version of Phantom wallet installed
2. Visit chainlinklabs.com

Expected results:

Not blocked

Actual results:

Blocked

<img width="807" alt="Screenshot 2024-09-17 at 10 20 17 PM" src="https://github.com/user-attachments/assets/ad9a8272-96cc-44ba-b6e3-19ece8850379">

**Comment by Reedme-21** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@bradford-m

**Comment by samg95-jpg** [comment]
Closing this request as the site in question is no longer blocked.
