### ISSUE TITLE
Unblock ethena.fi

### ISSUE THREAD

**Issue by deHB6** [phantom/blocklist#1363]
Our domain is currently being incorrectly blacklisted, however I don't see it in the code here.  It was on the eth-phishing-detect list but has since been removed.

**Comment by Reedme-21** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@deHB6

**Comment by samg95-jpg** [comment]
Closing this request as the site in question is no longer blocked.
