### ISSUE TITLE
Vercel.app is flagged?

### ISSUE THREAD

**Issue by KarloAldrete** [phantom/blocklist#1365]
![image](https://github.com/user-attachments/assets/9c18772f-3cc5-49b4-9aa1-c4e29860675d)

Why is the entire vercel.app paths locked?

this must be a severe mistake because a most of the platforms use React and some of them deploy on Vercel for main-testing...

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.
