### ISSUE TITLE
Please unblock debot.ai

### ISSUE THREAD

**Issue by lianghaijian** [phantom/blocklist#1366]
Hello phantom team, 
we are debot.ai development team, debot is a digital currency AI tool that helps users do investment analysis and automated investment, please help unblock our domain name, thank you.

website：
https://app.debot.ai 
https://pc.diting.ai

twitter: https://x.com/DitingData

**Comment by case-hub** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@lianghaijian

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.
