### ISSUE TITLE
Unblock https://chainflip-broker.io/

### ISSUE THREAD

**Issue by CumpsD** [phantom/blocklist#1368]
I am the developer of https://chainflip-broker.io/, this is a service on top of Chainflip to allow integrators to easily add Chainflip to their project. As of a few hours ago, I receive the following when I go to the site:

![image](https://github.com/user-attachments/assets/8a10254f-b9fa-418f-b9a2-9c1d24acde76)

This is not a malicious site. It is an infrastructure project. Please unblock this or tell me which extra info is needed to get it unblocked.

For some reason, I can't seem to find it in this repo though?

**Comment by case-hub** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@CumpsD

**Comment by samg95-jpg** [comment]
Closing this request as the site in question is no longer blocked.
