### ISSUE TITLE
unblock "*.soltools.ca"

### ISSUE THREAD

**Issue by ajaypalnitj** [phantom/blocklist#1373]
I am creating this site to offer tools like NF faucet, SPL token faucet etc on devnet and testnet. 
There is no mainnet dapp on it.

**Comment by case-hub** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@ajaypalnitj

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.
