### ISSUE TITLE
Unblock memsite.fun

### ISSUE THREAD

**Issue by Tutealga** [phantom/blocklist#1377]
This domain is currently being incorrectly blacklisted. It is an application to create memecoin websites, where the user have to pay a small amount for the creation of them

**Comment by case-hub** [comment]
Contact the official [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@Tutealga 
Support.
  {c}2024

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.
