### ISSUE TITLE
unblock https://marlnade-fi.site/

### ISSUE THREAD

**Issue by Ketrah444** [phantom/blocklist#1379]
Reviewing website of marinade

**Comment by case-hub** [comment]
Contact the official [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@Ketrah444 
Support.
  {c}2024

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.
