### ISSUE TITLE
unlock usdm.live

### ISSUE THREAD

**Issue by mattiascaricato** [phantom/blocklist#1383]
usdm.live is a legit site part of the [Mountain Protocol's](https://mountainprotocol.com/) USDM ecoystem and should not be blocked. I couldn't find any references to the site in any of the blocklists, so not sure why this is being blocked.

Steps to reproduce:

Have Phantom wallet installed
Visit https://usdm.live

Expected results:
Not blocked

Actual results:
Blocked

**Comment by case-hub** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@mattiascaricato 
Support.
  {c}2024

**Comment by mattiascaricato** [comment]
bumping this

**Comment by mattiascaricato** [comment]
Fixed, thanks
