### ISSUE TITLE
Unblock streamflow.finance

### ISSUE THREAD

**Issue by luijoy** [phantom/blocklist#1390]
Come on guys - a bit more care here would have been appreciated. We have been building on Solana for 3 years and are in top 10 for TVL on Solana. Please unblock immediately.

**Comment by casehub2** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@luijoy 
Support.

**Comment by samg95-jpg** [comment]
Closing this request as the site in question is no longer blocked.

**Comment by woodydeck** [comment]
> Closing this request as the site in question is no longer blocked.

It's still blocked for me.
