### ISSUE TITLE
Request to clear domain: dgntasy.com Ticket Number: 3716

### ISSUE THREAD

**Issue by 0xPuddi** [phantom/blocklist#1403]
Hello I'm Puddi, team member of dgntasy, a Radar Hackathon Project. Our associate wrote you an email to clear our domain from the phantom wallet alert. We are currently communicating with Dawn of the Blowfish Review Team Associate. He said to open a ticket with the number 3716 for verification.

Thank you for your understanding.

We would love to have dgntasy.com cleared, with all its subdomains (**.dgntasy.com) if it wouldn't be possible please clear www.dgntasy.com and dgntasy.com

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.
