### ISSUE TITLE
Request to remove nora642.com from the blocklist.

### ISSUE THREAD

**Issue by uwand** [phantom/blocklist#1404]
I'm Hugues Nkouatchet Wandji (hugues@noracle.io), founder and CEO of the web3 project Noracle (noracle.io) that implements a protocol on the blockchain enriched with AI predictive models.

We noticed that the site of a game from our ecosystem (nora642.com) was put in your blocklist, causing us huge damage. I would like to know what the reasons are and most importantly I want you, please to remove our link from your blocklist.

If you have any questions about our project or about NORA642 specifically, please feel free to address them to my personal email address: hugues@noracle.io

I’m looking forward to hearing from you in the hope of an expeditious resolution of this case.
Yours faithfully

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.
