### ISSUE TITLE
Request to remove op.noveairdrop.com/ from the blocklist

### ISSUE THREAD

**Issue by ZooHero500** [phantom/blocklist#1405]
I'm ZooHero(zoohero.dev@gmail.com).

Our project is called Nove, and its background management system (https://op.noveairdrop.com/) is mainly used for token distribution. We noticed that the background management system was included in your blacklist, which caused us great losses. I want to know the reason and kindly ask you to remove our link from the blacklist.

Our team is located in China. You can find my social media account at https://x.com/zooheroes. Although we are new to this field and our project is a private commercial project (the code is stored on GitLab), we are committed to maintaining high standards of code quality and security.

If you have any questions about the Nove project, please feel free to contact me through my personal email zoohero.dev@gmail.com. I look forward to solving this problem as soon as possible.

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.
