### ISSUE TITLE
Request to remove kiloex.dappos.com from the blocklist

### ISSUE THREAD

**Issue by AndyAdolf2100** [phantom/blocklist#1410]
Hello, I found our product domain has been blocked by your wallet. Link of product is https://kiloex.dappos.com/. 
KiloEx is our copartner.
Here is our PR for removing from MetaMask blocklist: https://github.com/MetaMask/eth-phishing-detect/issues/88903.
Our twitter: https://x.com/dappOS_com

Please remove it from blocklist asap, thank you.

Tweets: 
@ dappos
https://x.com/dappOS_com/status/1824403512014541166
https://x.com/dappOS_com/status/1780137894218465670
@ KiloEx_perp:
https://x.com/KiloEx_perp/status/1829834554640654349

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.
