### ISSUE TITLE
Request to add HavenFi.xyz to whitelist

### ISSUE THREAD

**Issue by cheliosooo** [phantom/blocklist#1416]
I'm launching a new dapp on solana that lets you leverage trade without risk of liquidation. Phantom is one of the wallets I support. Whenever I try to interact with the website using Phantom I get this warning that I would like to remove.

![image](https://github.com/user-attachments/assets/4c43ff17-f6e1-4860-ab85-173f707acd3b)

**Comment by casehub2** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@cheliosooo

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.
