### ISSUE TITLE
Peaq Portal Flagged as Malicious Website by Phantom Wallet

### ISSUE THREAD

**Issue by rohanranjan250613** [phantom/blocklist#1439]
I am experiencing an issue where the Peaq portal (https://portal.peaq.network/) is being flagged as a malicious website by the Phantom wallet. This is causing inconvenience for users trying to access the portal for legitimate purposes.

Details:

- Website URL: https://portal.peaq.network/
- Wallet: Phantom Wallet
- Issue: The website is incorrectly flagged as malicious, preventing users from accessing it.

Steps to Reproduce:

1. Open the Phantom wallet.
2. Attempt to access the Peaq portal using the provided URL.
3. Observe the warning message indicating that the site is malicious.

Expected Behavior:

The Peaq portal should be accessible without any warnings, as it is a legitimate website.

Additional Information:

Please investigate this issue to determine if the flagging is a false positive.
If necessary, I can provide further details or assist in any way to resolve this issue.
Thank you for your attention to this matter.

**Comment by fhvbreugel** [comment]
Yep same for me by Phantom wallet:

https://portal.peaq.network/
![image](https://github.com/user-attachments/assets/cf922a95-42f9-4d97-a20e-8ae37ddc015b)

**Comment by casehub2** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@fhvbreugel 
Support.

**Comment by casehub2** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your error.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@rohanranjan250613 
Support.
