### ISSUE TITLE
https://usetokenpay.com flagged as malicious although not on blacklist and not malicious

### ISSUE THREAD

**Issue by LucaUhu** [phantom/blocklist#1443]
### Phantom Wallet Extension Malfunction: Overview

We are experiencing an issue in which our website and its subdomains (https://usetokenpay.com) are being flagged as a malicious website by the Phantom wallet although our website or parts of it do not appear in any of the blacklists. This is causing inconvenience for users trying to access the portal for legitimate purposes.

**Details:**

Website URL: https://usetokenpay.com
Wallet: Phantom Wallet
Issue: The website is incorrectly flagged as malicious, preventing users from accessing it.
Our domain or any parts of it, such as "tokenpay", is not in any blacklist. The extension seems to be malfunctioning.
This unintended behaviour was observed on different devices and across Chrome and Firefox browser.

**Steps to Reproduce:**

Attempt to access https://usetokenpay.com through the browser.
Observe the warning message indicating that the site is malicious although the website does not appear in any of the blacklists.

**Expected Behavior:**

The TokenPay website should be accessible without any warnings, as it is a legitimate website.

**Additional Information:**

Please investigate this issue to determine if the flagging is a false positive. 
If necessary, I can provide further details or assist in any way to resolve this issue.
Thank you for your attention to this matter.

**Comment by casehub2** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@LucaUhu 
Support.

**Comment by samg95-jpg** [comment]
Please send an email to review@blowfish.xyz for further investigation.
