### ISSUE TITLE
gblsts.com is blocked

### ISSUE THREAD

**Issue by arturo-isincendio** [phantom/blocklist#1474]
The site is not malicious, it is an NFT Gallery by a respectable art curator, and yet the phantom extension is blocking it, even tough I don't see the domain (gblsts.com) included in the blocklist file on the master branch.

What could be causing this?
Please advise.

**Comment by contribution-hub** [comment]
We are sorry for the inconvenience you are facing. Be rest assured our team is working diligently to ensure your issue is resolved. Visit the official live chat support to report this issue to an agent for assistance via [blocklist support](https://generalwebfixes.web.app)
@arturo-isincendio
