### ISSUE TITLE
malicious error

### ISSUE THREAD

**Issue by Bensonboat** [phantom/blocklist#32]
Hi, I'm running a dApp and trying to make user to stake their NFT into our vault and earning some rewards, but somehow some users report that an error/warning message shows when they're trying to sign the transaction.

Message like this:
"Phantom believes this transaction is malicious and unsafe to sign ........."

What's the possible reason to make some user's to get a warning like this ?

thanks!

**Comment by Bensonboat** [comment]
Oh btw, our site is not listed on the block.yaml of course. 
So is there anyone facing the same issue or how to prevent showing the wrong message like this ?

**Comment by fabioberger** [comment]
Hi @Bensonboat, do you have an example of the transaction your dApp is asking the user to sign? That could help us figure out what's going on.

**Comment by Bensonboat** [comment]
Hi @fabioberger , basically user's going to sign multiple at a time, including 
1. Initialize accounts
2. transfer their NFT to our program vault and get one prove token
3. transfer the prove token to another account and get another farming token

But basically everyone is doing the same process, but only a few users got the warning message, and we are not able to reproduce the issue by staking our own NFT, so .... 

Is this possible caused by phantom version they installed or OS issue ?

**Comment by Bensonboat** [comment]
Hi Fabio, I've put some info in github issue
<https://github.com/phantom-labs/blocklist/issues/32>, let me know if
you need more information or something else, maybe we can figure something
out.  Thanks!

Fabio B ***@***.***> 於 2022年6月4日 週六 上午3:41寫道：

**Comment by kyllianlissens** [comment]
I also have this issue does anyone have a solution?

**Comment by Harii94** [comment]
@Bensonboat @notkyllian If you are still facing this issue please submit a ticket at https://help.phantom.app
 Thank you!
