### ISSUE TITLE
[Legitimate Site Blocked] discord-accounts.ru

### ISSUE THREAD

**Issue by mmoadvert** [phantom/blocklist#341]
Our site discord-accounts.ru poses no danger. We have been working since 2020. We sell clean new automatically registered Discord messenger accounts. According to search engines "google" and "yandex" we have leading positions in CIS countries. Please exclude the site from suspicious.
![image](https://user-images.githubusercontent.com/75162773/213266651-8da02c5a-80b7-4b21-8d9b-f17d052caa52.png)

**Comment by mmoadvert** [comment]
In metamask they blocked it for the same reason. Allegedly we are violating the rules of discord. And to start with, my site does not accept payments through metamask or phantom at all. There is no phishing or cheating on the site. The site has been tested for years and thousands of users.

And the rules of discord apply only to users of this social network. These rules can not prohibit the sale on any external sites. If discord deems that the accounts being sold violate their rules, they will block them. I don't understand why crypto wallets are getting involved here. 

And note the existence of tens of thousands of stores of accounts from many social networks. And I don't see them blocking for violating social network rules in metamask or phantom. So why should my store be blocked? What made it so different?

**Comment by mmoadvert** [comment]
On metamask, they recently removed the erroneous lockout.

1. There is no phantom payment on the site
2. Discord rules do not apply to external sites
3. The site has leading positions in search engines in the CIS
4. We have no cryptophishing and it is already verified by the staff of metamask

Our site is nowhere in the blacklists except for your cryptocurrency wallet. Please unblock.

**Comment by Harii94** [comment]
closing this issue since the website in question is not present on the blocklist anymore.
