### ISSUE TITLE
[Legitimate Site Blocked] my.ether-room.xyz

### ISSUE THREAD

**Issue by 0xQueso** [phantom/blocklist#402]
This has already been resolved at Metamask.
https://github.com/MetaMask/eth-phishing-detect/issues/11497

Wrongfully flagged domain. Thank you, please let me know how I can be of any help.

**Comment by 0xQueso** [comment]
@loucaslt Hi please can I ask for any update. thank you 🙏🏻

**Comment by Harii94** [comment]
Website still present in MM blocklist
![image](https://user-images.githubusercontent.com/98442113/221572099-7699226a-5ab2-46dd-bb56-35619ac7457d.png)

**Comment by 0xQueso** [comment]
Hi @Harii94, please have a look again. have been resolved recently 🙏🏻 https://github.com/MetaMask/eth-phishing-detect/commit/bd90a5d6d78e1076a4d106b430575c4e356faacc

**Comment by 0xQueso** [comment]
https://github.com/MetaMask/eth-phishing-detect/commit/b4a0f3f1e0f28e0488587d05789c436ed49122ab

**Comment by Harii94** [comment]
Closing this issue as the site is not present in the blocklist anymore.
