### ISSUE TITLE
[Legitimate Site Blocked] Exodus.icu - a Revolt Chat clone

### ISSUE THREAD

**Issue by brocksexton** [phantom/blocklist#498]
Hello!

I believe exodus.icu was automatically flagged due to its resemblance of exodus.com, or possible past use in phishing activities. I just recently registered the domain 2 days ago and plan to run my own personal instance of the Revolt Chat app. It's currently up and live now, and a few friends alerted me that MetaMask or Phantom are flagging it.

If I could request the flag be removed, that would be great. I also utilize a few subdomains such as https://app.exodus.icu/ https://autumn.exodus.icu/ https://docs.exodus.icu/ https://support.exodus.icu/ https://endpoint.exodus.icu/ and have plans to use a few others in the future.

**Comment by Harii94** [comment]
Hey, we source the website from Metamask [blocklist](https://github.com/MetaMask/eth-phishing-detect/blob/main/src/config.json)
