### ISSUE TITLE
Unblock 1inch.dev

### ISSUE THREAD

**Issue by alex1inch** [phantom/blocklist#508]
Hi 1inch.dev was bought 2 weeks ago by 1inch. Could you please unblock this site?

**Comment by alex1inch** [comment]
If the domain is blocked, because it was sourced by Metamask, could you please update it here, too.
It was removed there on July 7th https://github.com/MetaMask/eth-phishing-detect/commit/3cb9b2f4583635d95b78e4a2b083181be92824de

**Comment by Harii94** [comment]
Thank you, I just removed it from our blocklist.
