### ISSUE TITLE
Error in Blocklisting (BanterBubbles.com)

### ISSUE THREAD

**Issue by joshthetrader** [phantom/blocklist#510]
https://banterbubbles.com/ Hi there guys, hope you're well, we've just noticed our website being flagged as dangerous with malicious activity present.

I assure you this is not the case. Please visit our site and notice there are absolutely no requirements for any metamask or other wallet addresses. It's not even an available option.

Banter Bubbles is a platform we built for users in the Crypto Banter community to track major price movements in Crypto. We allow users to chat through use of their Twitter account.

Please correct this issue as it is causing major issues for our community.

Correspondence will be much appreciated

Best regards
Josh (Product Manager)

**Comment by Harii94** [comment]
Apologies for the delay in response, it looks like the domain is not blocked anymore.
