### ISSUE TITLE
[Legitimate Site Blocked] usdcswap.com

### ISSUE THREAD

**Issue by let-it-snow** [phantom/blocklist#528]
Our website [usdcswap.com](http://usdcswap.com/) was flagged as potentially deceptive [here](https://github.com/phantom/blocklist).
The website is owned and managed by Ultra Stellar and is linked to at the company website [ultrastellar.com](http://ultrastellar.com/)
This is a legitimate website however the USDC swap tool has been temporarily disabled some time ago. We are planning on resuming the operations over the next few months.
Please remove [usdcswap.com](http://usdcswap.com/) from this blocklist as soon as possible. [Metamask issue](https://github.com/MetaMask/eth-phishing-detect/issues/13363) link attached.

**Comment by Harii94** [comment]
Closing this request since the site is not blocked anymore.
