### ISSUE TITLE
Legitimate Site Block/Flagging - Bitcoinminetrix.com

### ISSUE THREAD

**Issue by TheBlockDevGroup** [phantom/blocklist#551]
Hi, the BitcoinMinetrix.com Website is wrongly being flagged as a Phishing site by Phantom. 

The site has not been reported on either your (https://github.com/phantom/blocklist/blob/master/blocklist.yaml) or the Metamask Block list.

This flagging is causing issues with our clients raise, damaging the companies reputation and slowing down the speed the bitcoin Minetrix community can claim their tokens. Please can you insure the site is unflagged and provide an explanation on why this has happened so we can insure there is no repeat of this going forward.

Thanks

**Comment by Harii94** [comment]
Closing this request as the site in question is not blocked anymore.
