### ISSUE TITLE
Website flagged as malicious and unsafe to use when it's not

### ISSUE THREAD

**Issue by bakaburg24** [phantom/blocklist#557]
Hello, 

As of today, our website is being flagged by Phantom as malicious and unsafe to use. We provide a service for the solana ecosystem and offer up services for staking, games ect.. I can't seem to find the website being flagged in the blocklist, so i'm not sure why it's throwing this error on chrome? Can anyone please help us? It's scaring away folks using our services. 

PS: We're multi-tenant so the way the website operates is via subdomain, {project}.solsuite.io represents each project. 

Thanks,
Baka

**Comment by Harii94** [comment]
Hey @bakaburg24, I just checked and it doesn't appear to be blocked anymore. Can you please confirm?
Thanks!
