### ISSUE TITLE
Non-blacklisted website is blocked in Phantom extension

### ISSUE THREAD

**Issue by ardier16** [phantom/blocklist#562]
**Description**
The website https://qdev.li and all its subdomains are blocked when using the Phantom extension in Google Chrome. However, the domain is not present in the blacklist file. Could you please explain what is the reason of this website being blocked?

**Screenshot**
<img width="400" alt="Screenshot 2023-11-09 at 16 08 39" src="https://github.com/phantom/blocklist/assets/17788043/975439d6-680d-40ae-a77b-3f47363c2948">

**Details**
App: Phantom Chrome Extension
Version: 23.16.1

**Comment by FSMa5ter** [comment]
As part of the Q community, it would be great to understand why the domain is blocked. Many thanks!

**Comment by benebrn** [comment]
I was surprised to see this, as Q is a legitimate project. Thanks for looking into this.

**Comment by Harii94** [comment]
Thanks for flagging, this should be fixed now.

Apologies for any inconvenience this might have caused you 🙏
