### ISSUE TITLE
google sso popup in chibi.gg is blocked

### ISSUE THREAD

**Issue by shirai91** [phantom/blocklist#563]
Description
The website https://chibi.gg and the google sso popup is blocked when using the Phantom extension in Google Chrome. However, the popup domain is a firebase domain (chibi-clash-prod.firebaseapp.com), and it is not present in the blacklist file. Could you please explain what is the reason of this website being blocked?

Screenshot
![image](https://github.com/phantom/blocklist/assets/8848513/808cd983-c8a5-4757-b6ee-b08111a31fae)
![image](https://github.com/phantom/blocklist/assets/8848513/dfee1bf4-1338-40a2-a30e-d82daecb3b07)

Details
App: Phantom Chrome Extension
Version: 23.16.1

**Comment by fernandoc4f** [comment]
The same happens to me

**Comment by fernandoc4f** [comment]
> The same happens to me

I've sent a PR to include the firebase.app to the whitelist. Maybe in a few days the issue is fixed

**Comment by Harii94** [comment]
This is fixed.
