### ISSUE TITLE
[Legitimate Site Blocked] meshtrade-development.firebaseapp.com - Google SSO

### ISSUE THREAD

**Issue by LawrenceMarsman** [phantom/blocklist#565]
Our Google Single Sign-On (SSO) popup (accessible at https://meshtrade-development.firebaseapp.com/) is being blocked when the Phantom extension is installed in Google Chrome, as shown in the attached screenshot.

However, the popup’s domain is a Firebase domain, and I’ve confirmed that it’s not listed in the Phantom extension’s blacklist file. Could you please help me understand why this website is being blocked?

**Comment by Harii94** [comment]
This should be fixed now, sorry for the inconvenience!
