### ISSUE TITLE
[Legitimate Site Blocked] *.gib.work

### ISSUE THREAD

**Issue by anthonyliriano** [phantom/blocklist#569]
Hi, we're getting ready to go to mainnet and we're currently getting blocked. https://app.gib.work/create

https://twitter.com/gib_work

![image](https://github.com/phantom/blocklist/assets/27873749/021467f5-8f6c-4f1b-857c-2c599634d089)

**Comment by Harii94** [comment]
Hi @anthonyliriano I just checked and it doesn't appear to be blocked. Can you please confirm?
