### ISSUE TITLE
Well known sites should suggest redirects similar to what Google Safebrowsing does

### ISSUE THREAD

**Issue by kdenhartog** [phantom/blocklist#577]
I was just trying to go to Metamask's site and got confused why Phantom was blocking this. Turns out I had the wrong site (thank you for blocking it!) and it made me think an improvement for some of these well known sites would be to suggest a redirect to the assumed site the user was trying to ask. In this case, the incorrect impression I had at first glance was trying to figure out why one wallet was blocking another and having a suggestion to the right site may help alleviate that impression.

![Screenshot 2023-11-24 at 10 10 18 AM](https://github.com/phantom/blocklist/assets/23125059/d1df0b83-c907-482a-8085-a716129fcee9)

**Comment by lekkerelou** [comment]
Because it's metamask.io not .com :)

**Comment by Harii94** [comment]
Thanks for the suggestion! I'll pass it along to the team.
