### ISSUE TITLE
linux.org.ru blocked by mistake?

### ISSUE THREAD

**Issue by zezic** [phantom/blocklist#579]
The following Linux-related news site is now blocked by Phantom extension in my browsers (Firefox, Chromium).

https://www.linux.org.ru

But I can't find the mention of this domain in blocklist. What happened?

<img src="https://github.com/phantom/blocklist/assets/1945127/cf042e68-67e5-4cb0-9205-e40cfa597dc9" width="250" alt="Firefox">
<img src="https://github.com/phantom/blocklist/assets/1945127/3dbff182-97c2-4baa-8e8a-4b50a8cefe59" width="250" alt="Chromium">

**Comment by Harii94** [comment]
This is fixed now.

Apologies for any inconvenience this might have caused you 🙏
