### ISSUE TITLE
*.underground.enterprises falsely blocked

### ISSUE THREAD

**Issue by emmsixx** [phantom/blocklist#580]
I was hired by the Underground team for some webdev work and I recently launched new website but seems that the entire domain is blocked now.

Root domain is just a landing page/info site I made. 
Only subdomain that has a live site at the moment is the burn that the team is conducting for one of their NFTs.

Can provide more information if needed, but would appreciate if this could be resolved A.S.A.P.

Thanks!

**Comment by Harii94** [comment]
This is resolved. Apologies for any inconvenience this might have caused you 🙏
