### ISSUE TITLE
app.deform.cc accidentally getting blocked

### ISSUE THREAD

**Issue by keikumata** [phantom/blocklist#581]
Hey folks! My name is Kei and I'm the co-founder of a web3 forms product called DeForm (https://deform.cc/).

Our domain is deform.cc and our main app is on app.deform.cc. Unfortunately, it looks like the blocklist (https://github.com/phantom/blocklist/blob/master/blocklist.yaml) shows `app-deform.cc`, which seems to actually be a known malicious website.

While `app-deform.cc` (the scam website) and `app.deform.cc` (our legitimate app's URL) are different, our users are complaining that the Phantom wallet extension is blocking access to our forms.

Here's an example form run by the Farcaster team with the URL: https://app.deform.cc/form/5ccff9d9-9435-42da-bf0f-507e13cd0597/

![image](https://github.com/phantom/blocklist/assets/9777166/6ddbf69a-44cb-41b6-8862-d701f7e428d3)

Is there anyway to explicitly whitelist `app.deform.cc`? Happy to provide more credentials to prove that we aren't malicious and are trying to run a legitimate product for the betterment of the web3 industry :)

More info about me:
- Twitter: https://twitter.com/keikumata
- LinkedIn: https://www.linkedin.com/in/keiyoshikoshi/

cc: @lfernandezpt since it seems like you manage the blocklist :) thanks for your great work and keeping the community safe!

**Comment by Harii94** [comment]
This is fixed, apologies for any inconvenience this might have caused you 🙏
