### ISSUE TITLE
join3.top block by mistake

### ISSUE THREAD

**Issue by join3top** [phantom/blocklist#583]
<img width="815" alt="image" src="https://github.com/phantom/blocklist/assets/152862466/7ce415b4-ebb5-4074-82d7-a1de57b2873e">

<img width="1479" alt="image" src="https://github.com/phantom/blocklist/assets/152862466/1aa22be8-a3b8-4eae-b72a-2aad3c955c5a">

**Comment by Harii94** [comment]
This is fixed.
