### ISSUE TITLE
My Website is blocked but it’s safe 

### ISSUE THREAD

**Issue by FunkyXLabs** [phantom/blocklist#585]
Hi Phantom Team ,

https://bringbacknfts.com/mint

my website is being blocked by phantom. I do not know why this happen. We are a legit project and our nft mint is through bueno.art which is a respectable and safe launchpad. 

Can you please review it and get the block off? We have minted almost 300 NFTs with no issues and now we are in the middle of a launch

thanks 
Frankie

**Comment by Harii94** [comment]
It looks fine from my end. Can you please confirm?
