### ISSUE TITLE
github.dev web-based editor is being flagged

### ISSUE THREAD

**Issue by 0xDlyan** [phantom/blocklist#588]
Hi, 

[github.dev web-based editor ](https://github.dev/github/dev)is being flagged has malicious by Phantom Browser extension, the first time it is being detected.

Could you please take a quick look ?

Regards,

![SCR-20231211-euz](https://github.com/phantom/blocklist/assets/47043212/37a8dce3-f216-425b-bb0d-112580d78fe1)

**Comment by Harii94** [comment]
Hey @0xDlyan, this is fixed. 

Apologies for any inconvenience this might have caused you 🙏

**Comment by 0xDlyan** [comment]
Thank you!
