### ISSUE TITLE
RMG users reporting that rmg.io is blocked for some reason

### ISSUE THREAD

**Issue by coffee-converter** [phantom/blocklist#606]
rmg.io seems to now be flagged in Phantom...  Why is that?

**Comment by bryanjcampbell1** [comment]
Why is this blocked?

**Comment by victorchika** [comment]
Nothing is wrong with rmg. Remove error

**Comment by devinlovato** [comment]
Please remove flag. It is on domain and all subdomains

**Comment by Konovahr** [comment]
What happened? Why put a flag on this? Never had any issues with their sites. Someone needs to help out here

**Comment by Beavemeister** [comment]
I don't see any reason for rmg to be flagged.

**Comment by Harii94** [comment]
Closing this request as the site in question is not blocked anymore.
