### ISSUE TITLE
Main wallet of NEAR protocol blocked

### ISSUE THREAD

**Issue by banzai2k** [phantom/blocklist#634]
It's the one they recommend after they shut their own wallet down in January.
https://app.mynearwallet.com/

Please unblock urgently.

**Comment by SteveKok** [comment]
Hi, I am a developer from My Near Wallet.

Recently our website had been flooded with some Fungible Tokens with weird symbol and name, trying to mislead user to some of the phishing sites, which looks like My Near Wallet...

We have solve the issue in this commit:
https://github.com/mynearwallet/my-near-wallet/commit/8243f8c3284ea1edee9e4ca3fa3e20f51fba95c8

And the commit is currently already active on our website.

We hope that mynearwallet can be removed from the blacklist soon.

**Comment by Harii94** [comment]
Closing this request as this site in question is not blocked anymore.
