### ISSUE TITLE
[Block Domain]

### ISSUE THREAD

**Issue by wikipizzer** [phantom/blocklist#664]
solana-experting[.]com, infra for "riddance drainer" kit, can be found at stakingorca[.]finance and others

drainer[.]gg, infra for "chick drainer" kit, can be found at bonksclaim[.]com and a looot more fake bonk pages

both are sol focused drainers

Side note, these blocks would have way more impact if the blocking was done on network level, like uBlock Origin, instead of redirecting the user away when they load the page.

**Comment by Harii94** [comment]
Thanks for the sharing this @wikipizzer
