### ISSUE TITLE
Unblock dexscreener.com

### ISSUE THREAD

**Issue by alexandrebini** [phantom/blocklist#721]
Hi there,

It looks like https://dexscreener.com got into the block list. I would like to get it removed.

Could you please let me know what you need to get it unblocked?

Best,

**Comment by SynidSweet** [comment]
I second this. I also got it blocked and would like it removed.

Thanks!

**Comment by isco0zjj** [comment]
yes please

**Comment by nikdeveloper1555** [comment]
Yes!
No need to block it!

**Comment by rtunazzz** [comment]
+1

**Comment by ttirty** [comment]
I want to know why I got banned. Is it a wrong submission?

**Comment by ttirty** [comment]
I want to know why dexscreener was banned. Is it a wrong submission?

**Comment by chriskalani** [comment]
Hey there, we're looking into it now. We use a number of different blocklists, I don't see [dexscreener.com](https://dexscreener.com/) on our list. Do you see it in this repo? Either way we will get it fixed asap!

**Comment by SynidSweet** [comment]
![image](https://github.com/phantom/blocklist/assets/66042563/5440bf54-d9b6-4963-b7f3-8b3551795d8b)

This is what I got in chrome. Sent me to this repo.

**Comment by alexandrebini** [comment]
@chriskalani did you find where is it coming from?

**Comment by bfriel** [comment]
Hi @alexandrebini this is now resolved and dexscreener.com is unblocked. This came from a third-party security service we use as an added layer to this blocklist repo. We made sure that partner has removed it. Sorry for the inconvenience!

**Comment by alexandrebini** [comment]
@bfriel I really need to know what service is that so we make sure it won't happen again. Would you mind sharing it?

**Comment by bfriel** [comment]
> @bfriel I really need to know what service is that so we make sure it won't happen again. Would you mind sharing it?

Yes, we just followed up via DM from our [Company account](https://twitter.com/phantom) to [DexScreener](https://twitter.com/dexscreener)
