### ISSUE TITLE
[Legitimate Site Blocked] CryptoLink.Tech

### ISSUE THREAD

**Issue by cletusCLT** [phantom/blocklist#739]
Hello, my name is Cletus. I manage the operations of CryptoLink.Tech, a cross-chain interoperability protocol.

Some of our community members have pointed out that Phantom is flagging our dApp and landing page. We are a legitimate project that has been in operation for over 2 years now. Flagging our website is a mistake.
 
Please let me know what needs to be done to get this issue resolved.

You can contact me at cletus@cryptolink.tech

Links for your reference:
Landing page: https://cryptolink.tech/
dApp: https://app.cryptolink.tech/

Thank you,
Cletus
COO
CryptoLink

**Comment by Harii94** [comment]
Closing this request as the site is no longer blocked.
