### ISSUE TITLE
Unblock AVAX network explorer Snowtrace

### ISSUE THREAD

**Issue by mark-ht** [phantom/blocklist#740]
Snowtrace is the go to explorer for the AVAX network https://snowtrace.io/.

Phantom as of today for me has started flagging it as a suspicious site. I am unable to find references to it in your blacklist files so it would seem it's one of the third party services you're using flagging it in error, similar to dex screener.

![image](https://github.com/phantom/blocklist/assets/49837915/c1e1e1d5-8e1f-4bfc-8461-7ae0abc7b8b5)

**Comment by Leilani432** [comment]
Hello @mark-ht if it’s a Avax related issue i will suggest you contact an Avax support like i did and got help on their general chain link [Avax Live Support Agent](https://solutiondesk.live/avax) 
You can use the  ticket ID DR3486 as well for a faster response.

**Comment by Harii94** [comment]
Closing this request as it has been fixed.
