### ISSUE TITLE
[Legitimate Site Blocked]  l2telegraph.xyz

### ISSUE THREAD

**Issue by walruzperil** [phantom/blocklist#755]
website legit l2telegraph.xyz

**Comment by Harii94** [comment]
The site is currently on the Metamask blocklist.  If this is removed, we will automatically be able to unblock the site.

**Comment by walruzperil** [comment]
Metamsk has remove domain from blocklist. https://github.com/MetaMask/eth-phishing-detect/pull/15026
But phantom still blocking
