### ISSUE TITLE
multi tenant site domain flagged

### ISSUE THREAD

**Issue by TD-Syndicure** [phantom/blocklist#758]
The app I have built for Sol Suites (a Jelly Co sub project) has had its domain flagged.

The domain is: solsuiteupgrades.com

The app is a trait swapping platform operated as a multi tenant app through subdomains.
"*.solsuiteupgrades.com" will need to be whitelisted.

Carlos from Jelly Co can be contacted to confirm this.

**Comment by Harii94** [comment]
Closing this request as the site is no longer blocked.
