### ISSUE TITLE
Unblock *.nfts2.me

### ISSUE THREAD

**Issue by nfts2me** [phantom/blocklist#762]
The whole domain (and it subdomains) seems that this is wrongly blocked.
This is the domain for the collections created using https://nfts2me.com/, in the form of collection_name.nfts2.me

All websites under this subdomain are controlled by us and are secure. The only thing we can't control is the content of them. We are permissionless, so we can't control what the users create.

But we have an [abuse@nfts2me.com](mailto:abuse@nfts2me.com) mail that is being used to block their minting pages (we can't do anything about the contracts on the blockchain) when the user creates something that may infringe intellectual property.

If you need any further information, please, let us know.

**Comment by Harii94** [comment]
Hi,

This appears to be resolved now, please reopen if the issue persists.
