### ISSUE TITLE
unblock arweave.net

### ISSUE THREAD

**Issue by frostypeng** [phantom/blocklist#779]
![image](https://github.com/phantom/blocklist/assets/81419087/8fe66fcc-8448-4c08-976f-eab2485a743e)

**Comment by frostypeng** [comment]
Why is it getting blocked? I couldn't find it in [blocklist.yaml](https://github.com/phantom/blocklist/blob/master/blocklist.yaml)

**Comment by scarceproject** [comment]
Really weird that's arweave.net is blocked. Arweave.net is widely used by the Solana community to store metadata. This shouldn't be blocked.

**Comment by Harii94** [comment]
Apologies, this has been added to our whitelist.
