### ISSUE TITLE
Blocklist removal mysellix.io

### ISSUE THREAD

**Issue by danieleServadei** [phantom/blocklist#791]
Hello there; the Phantom block error is received when trying to access any MySellix subdomain (e.g. https://daniele.mysellix.io).

As a general description, Sellix is a SaaS eCommerce website that focuses on cryptocurrency payments and digital goods (https://sellix.io). We use the mysellix.io domain to handle merchant stores (similar to myshopify.com).

We also do not see any mention of `sellix` or `mysellix` inside the blocklist.yaml file in this repository, so we're unsure whether this is an ongoing issue.

We have a few thousand active merchants and are using Phantom to streamline the checkout experience on our invoices (see attached).

We'll also open a PR with the domains to be approved.

Thank you.

<img width="1720" alt="CleanShot 2024-01-23 at 19 13 56@2x" src="https://github.com/phantom/blocklist/assets/25457567/14b8b16a-3900-4f5a-b2c1-be833e8ec471">

<img width="552" alt="CleanShot 2024-01-23 at 19 19 43@2x" src="https://github.com/phantom/blocklist/assets/25457567/52f9a7e5-79e6-46e9-8acc-c084e1a5ed31">

<img width="614" alt="CleanShot 2024-01-23 at 19 19 48@2x" src="https://github.com/phantom/blocklist/assets/25457567/fb15aad0-9dfe-4edd-a53e-d3d5c6597e12">

**Comment by danieleServadei** [comment]
@MYRoandrew not yet, hopefully they see this

**Comment by Harii94** [comment]
This is fixed ✅ 

Apologies for any inconvenience this might have caused you 🙏

**Comment by danieleServadei** [comment]
@Harii94 this is happening again now, can we be added to a whitelist?
