### ISSUE TITLE
[Legitimate Site Blocked] anitaonsol.com

### ISSUE THREAD

**Issue by MYRoandrew** [phantom/blocklist#793]
My website (https://anitaonsol.com/) has been flagged without reason. We're running a legitimate presale for a memecoin on Solana, and everything is in compliance. Kindly remove the flag ASAP. We already have many followers on X and becasue of the flag people are thinking its a phising website . 

How can phantom flag a legitimate website ??

**Comment by Harii94** [comment]
Closing this request as the site in question is not blocked anymore.
