### ISSUE TITLE
Any plans regarding providing urls by the public endpoint?

### ISSUE THREAD

**Issue by faridmovsumov** [phantom/blocklist#8]
Hello, love this initiative, I am wondering if you have any plans to serve this information over the HTTP endpoint so apps that will integrate can fetch fresh data easily.

**Comment by AlwaysBCoding** [comment]
hey, sorry for the delayed response. What would be the use-case of an app needing to fetch the blocklist data in real-time? If there's a good use case for it, I think it's very possible that we could expose a public HTTP endpoint for it

**Comment by faridmovsumov** [comment]
Hello @AlwaysBCoding , thank you very much for the reply. I am building https://nftbucket.com/ which allows people to create their own nft galleries. I am importing all these nfts into my website to make it visible on the gallery of users. I would like to use your API endpoint to get a full list of blocked domains to compare it with the external_url metadata field of the URL. Scammers mostly put their malicious website to this field so when people click on it they go to that website. In this way, I can prevent all websites which added to your list. I am currently fetching directly your YAML but parsing it is not working smoothly I need to do some tricks to make it work. I think if JSON output is provided it will be super helpful and others also can benefit from it.

**Comment by faridmovsumov** [comment]
Current implementation example if someone is interested how I am using this repository without endpoint.

```php
<?php

namespace App\Utils\Nft;

use Symfony\Component\Yaml\Yaml;

class ScamPrevention
{
    const SCAM_URL_SOURCE = 'https://raw.githubusercontent.com/phantom-labs/blocklist/master/blocklist.yaml';

    private static array $scamWebsites = [];

    private static array $scamNftNames = [
        'NFT'
    ];

    public static function isScamNft(array $nftMetadata): bool
    {
        if (empty($nftMetadata['external_url'])) {
            return false;
        }

        $website = $nftMetadata['external_url'];
        $website = preg_replace("(^https?://)", "", $website);
        $website = str_replace('www.', '', $website);

        if (in_array($website, self::fetchListOfScamWebsites())) {
            return true;
        }

        if (!empty($nftMetadata['name']) && in_array($nftMetadata['name'], self::$scamNftNames)) {
            return true;
        }

        return false;
    }

    public static function fetchListOfScamWebsites(): array
    {
        if (!empty(self::$scamWebsites)) {
            return self::$scamWebsites;
        }

        try {
            $scamWebsitesAsYaml = file_get_contents(self::SCAM_URL_SOURCE);
            $parsedWebsites = Yaml::parse(str_replace(': ', '', $scamWebsitesAsYaml));
            $parsedWebsites = str_replace('- url', '', $parsedWebsites);
            self::$scamWebsites = explode(' ', $parsedWebsites);
        } catch (\Throwable $throwable) {
            self::$scamWebsites = [];
        }

        return self::$scamWebsites;
    }
}
```

**Comment by b12e** [comment]
@faridmovsumov There's already such a section though (in response to your last comment):
<img width="366" alt="image" src="https://user-images.githubusercontent.com/1340823/222270736-8b1390a9-acb0-403e-b38a-8d56c904e005.png">
