### ISSUE TITLE
[Legitimate Site Blocked] mero.finance

### ISSUE THREAD

**Issue by chase-manning** [phantom/blocklist#850]
https://mero.finance/

Our website suddenly has a large error showing. We are a reputable protocol that has been in production for several years now. Please can you remove this error?

- Our docs: https://docs.mero.finance/gitbook/
- Twitter: https://twitter.com/merofinance
- Discord: https://discord.com/invite/jpGvaFV3Rv
- GitHub: https://github.com/merofinance

<img width="807" alt="image" src="https://github.com/phantom/blocklist/assets/53957795/43ec9133-ce69-4708-bb07-592a72cf469e">

**Comment by louiscl** [comment]
Would be great if we could resolve this issue asap. Chase shared our socials with you, so please don't hesitate to contact us should you have any further questions.

**Comment by Harii94** [comment]
Closing this request as the site in question is no longer blocked.
