### ISSUE TITLE
Please unblock Zerolend.xyz

### ISSUE THREAD

**Issue by deadshotryker** [phantom/blocklist#851]
There are a lot of scam sites representing our domain, but ZeroLend.xyz is the legitimate one. 

Check on twitter.com/zerolendxyz -> url

We have made a PR for this: https://github.com/phantom/blocklist/pull/852

![image](https://github.com/phantom/blocklist/assets/151393124/d0d91289-e80c-4a3a-99b6-e9983831ea38)

**Comment by Harii94** [comment]
Closing this request as the site in question is not blocked anymore.
