### ISSUE TITLE
[Legitimate Site Blocked] www.metaxseed.io

### ISSUE THREAD

**Issue by metaxseed** [phantom/blocklist#877]
https://www.metaxseed.io/

Hi,

We are a legitimate site and have been running for over two years. I am not sure what triggered this site to be blocked but it is inaccurate and should be removed from the blocked list.

If you have any questions, you can reach us at

[contact@metaxseed.io](mailto:contact@metaxseed.io)

Our link tree: https://linktr.ee/metaxseed
Our medium: https://medium.com/metaxseed-games
CEO LinkedIn: https://www.linkedin.com/in/shipon-chowdhury-1a669118

![image](https://github.com/phantom/blocklist/assets/99299293/81b9aaf7-5466-4cfc-99f7-f47b42e8f6ba)

![image](https://github.com/phantom/blocklist/assets/99299293/a2b515c6-7b78-4106-ae5c-b61c1212a8c8)

![image](https://github.com/phantom/blocklist/assets/99299293/d10db3b0-608a-4ad8-a312-94aaab5b1438)

**Comment by Harii94** [comment]
Closing this request as the site in question is no longer blocked.
