### ISSUE TITLE
Legitimate Site Blocked

### ISSUE THREAD

**Issue by huncholane** [phantom/blocklist#929]
Dear Phantom Admin Team,

We hope this message finds you well. We are writing to request the removal of https://salesquest.io from your blocklist. Our project is aimed at revolutionizing the sales engagement industry, offering innovative features and solutions.

You can learn more about Sales Quest by visiting our presentation website at https://salesquest.io. Our presale is currently hosted on the app subdomain at https://app.salesquest.io/presale/, and are launching it tomorrow on the 16th. 

For further details about our project, please visit https://docs.salesquest.io. We are excited about the opportunity to share our vision and would be grateful for your approval.

Thank you for considering our request. We look forward to your response.

Best regards,
Sales Quest Team

**Comment by Xander337** [comment]
I do not understand why https://salesquest.io/ and https://app.salesquest.io/presale/ are being blocked by Phantom. We are not listed on the Master Blocklist https://github.com/phantom/blocklist/blob/master/blocklist.yaml and just launched the website last Friday on the 10th of Feb.

Please let us know why this happening and how to correct asap, we now have to delay our presale start date to get this corrected. 

Thank You, 
Xander Andre
Founder ♾ Sales Quest

**Comment by Harii94** [comment]
Closing this request since the site in question is not blocked anymore.

**Comment by Xander337** [comment]
May I ask why we were blocked and not visible on the master blocklist.yaml, it's a bit concerning. 

I thought this was a decentralized wallet.
