### ISSUE TITLE
Still Get the Blowfish Error and Blocked Page Popup

### ISSUE THREAD

**Issue by huncholane** [phantom/blocklist#933]
Closing this request since the site in question is not blocked anymore.

_Originally posted by @Harii94 in https://github.com/phantom/blocklist/issues/929#issuecomment-1948737396_
            
Hey, 

We're still getting the blocked page errors for https://salesquest.io and https://app.salesquest.io. Thank you in advance for your prompt attention.

Sincerely, 
Sales Quest Team

**Comment by Harii94** [comment]
@huncholane please drop an email to review@blowfish.xyz, thanks!
