### ISSUE TITLE
Legitimate Site Blocked

### ISSUE THREAD

**Issue by diklou** [phantom/blocklist#936]
We are a legitimate Solana node provider. You can join our discord [here](https://discord.gg/yFvXSk4Sd3), and check out our #success channel.

Our dashboard is hosted at [dashboard.pikanode.io](dashboard.pikanode.io) & our minting website is being hosted on [launch.pikanode.io](launch.pikanode.io)

this started happening when I was setting up a test mint site on devnet, we got flagged by blowfish.xyz for idk what reason.
Please remove the warning from the dashboard & mint site mentioned above.

**Comment by Harii94** [comment]
Closing this issue since the site in question is not blocked anymore.
