### ISSUE TITLE
cloudflare.com blocked

### ISSUE THREAD

**Issue by skyy-codes** [phantom/blocklist#937]
cloudflare.com is blocked so dumb

**Comment by Jazb** [comment]
If I can confirm the same issue here, there is a Cloudflare block if it exists explicitly in any of the lists.

**Comment by tracy-codes** [comment]
Confirming same thing here

**Comment by jstnw10** [comment]
Wondering if Cloudflare tunnels are generally affected too, cause my tunnel domain is flagged as well 💀

**Comment by JackCrispy** [comment]
Why is phantom acting as a browser safeguard? I never enabled this functionality in the extension or can even find a setting to disable it.

**Comment by avral** [comment]
....

**Comment by Harii94** [comment]
This has been fixed! Sorry for the inconvenience caused 🙏
