### ISSUE TITLE
Google.com is blocked..

### ISSUE THREAD

**Issue by JackCrispy** [phantom/blocklist#940]
![image](https://github.com/phantom/blocklist/assets/34707863/444785b9-7d65-4021-bdc7-67382a77d5d7)

Hey guys, here's the issue. Uninstalling phantom now. Thanks!

**Comment by JakkuSakura** [comment]
Fuck phantom. Same issue

**Comment by hirakujira** [comment]
This is hilarious.

**Comment by JackCrispy** [comment]
Yesterday it was cloudflare, now google. shame

**Comment by drewtunney** [comment]
duplicate of #942

**Comment by JackCrispy** [comment]
> duplicate of #942

how can this be a duplicate if 942 is 2 numbers after 940.
