### ISSUE TITLE
Who thought google.com is a phishing link 😭😭

### ISSUE THREAD

**Issue by SwayStar123** [phantom/blocklist#942]
![image](https://github.com/phantom/blocklist/assets/46050679/c5b085d5-36f7-4c12-a003-e70f37adb82f)

**Comment by Ryckie** [comment]
Yep, if it's soo easy to push this shit thru, I don't trust this phantom project at all anymore. Deleting it. Wt*..

**Comment by josephtaylor** [comment]
I can understand a blocklist on the mobile browser but desktop is madness. Is there an opt out?

**Comment by MontyFlange** [comment]
yer , turned off now

**Comment by MontyFlange** [comment]
I got ripped off anyway . Voice.com said to move all my NFTs to this and then nothing happened and they all disappeared

**Comment by Xoni30** [comment]
Deleting phantom anyway.

**Comment by JackCrispy** [comment]
> I can understand a blocklist on the mobile browser but desktop is madness. Is there an opt out?

Nope. No opt out, extension in the 🗑️

**Comment by CloudMunk** [comment]
Yea this is how malicious software can make it to prod, deleting Phantom and moving all funds, thanks but no thanks👍
