### ISSUE TITLE
mbcstaking.com

### ISSUE THREAD

**Issue by ucelme** [phantom/blocklist#948]
Hello. Can you unblock https://mbcstaking.com/ website? I'm founder of Mad Bears Club company (https://twitter.com/madbearsclub) adn we built a staking website for my MBC token with the partnership of Armada (https://twitter.com/ArmadaFi).

**Comment by ucelme** [comment]
> Hello. Can you unblock https://mbcstaking.com/ website? I'm founder of Mad Bears Club company (https://twitter.com/madbearsclub) build staking website for my MBC token with the partnership with Armada (https://twitter.com/ArmadaFi).

**Comment by Harii94** [comment]
Hey @ucelme, please drop an email to review@blowfish.xyz to investigate further. Thanks!
