### ISSUE TITLE
Unblock remyswap.com

### ISSUE THREAD

**Issue by RemyToken** [phantom/blocklist#953]
Our website remyswap.com is getting blocked by Phantom.
In the site we used Jupiter Terminal, and made a few simple design changes.
The website is not finshed yet, but I would like to get it unblocked before continuing my work.
The source code is public and can be viewed on my profile: The repository called "remyswap.github.io".
Please let me know what I can do to get it unblocked.

Thanks :)

**Comment by JakkuSakura** [comment]
Hi, remyswap.github.io gave me 404 error

**Comment by RemyToken** [comment]
> Hi, remyswap.github.io gave me 404 error

Thanks for your response.
"remyswap.github.io" is the github repository name. I'm hosting the app using Vercel, so maybe that is why the domain remyswap.github.io doesn't work.
But the domain name remyswap.com should work. I paid for the domain and linked it to the repo.

**Comment by Harii94** [comment]
Hey @RemyToken, please write to review@blowfish.xyz to investigate further.
