### ISSUE TITLE
Unblock troontech.com

### ISSUE THREAD

**Issue by ObjectPlayer** [phantom/blocklist#958]
Hey Phantom Team, 

We have integrated multiple wallets on our site which includes Phantom Wallet too. We have deployed our frontend application on sub domain of troontech.com. After deployment, we have noticed that Phantom wallet has blocked our site. 
Kindly unblock our site. Let me know if you need further details about our application.

Thanks

**Comment by Harii94** [comment]
Hey @ObjectPlayer, please write to review@blowfish.xyz to investigate further.

**Comment by ObjectPlayer** [comment]
Sure @Harii94, Thanks for the quick response
