### ISSUE TITLE
Unblock nftytoolkit.com

### ISSUE THREAD

**Issue by chonbon** [phantom/blocklist#964]
Hello, I am the creator of nftytoolkit.com, right now the site is primarily being used for people to connect their discord and wallets together with my role verification service. But the site also has helpful tools for creators to help them create and manage nft projects on solana! Its a work in progress and a side project for me but it is weird that it got added to the blocklist when I am not even doing any transactions? I am simply asking the user to sign a message to verify identity when linking discord and a wallet. I can make my project public if you would like, just let me know what you may need from my end!

**Comment by Harii94** [comment]
Hey, could you please drop an email to review@blowfish.xyz to investigate further?
