### ISSUE TITLE
Unblock: blastman.xyz

### ISSUE THREAD

**Issue by rishabhkeshan** [phantom/blocklist#966]
Hey, we are a project launching on Blast today with a NFT collection of 10K, not using any malicious code, do look into how and why it got flagged as unsafe.

**Comment by codebuster22** [comment]
We are happy to share codebase for your due diligence. We are launching today, we cannot afford to be blocklisted today.

**Comment by Harii94** [comment]
Closing this request as the site in questions is not blocked anymore.
