### ISSUE TITLE
Domain blocklisted - Production DAPP

### ISSUE THREAD

**Issue by kazyon** [phantom/blocklist#978]
Hello i have the following DAPP https://www.a-nft.world. I spoke with somebody from review@blowfish.xyz over the email and i wanted this domain registered because it's a live environment and project.

I haven't found my domain in the blocklist.yaml file. 

Looking forward to your help.

**Comment by Harii94** [comment]
Closing this request as the site in question is no longer blocked.

**Comment by kazyon** [comment]
thank you !
