### ISSUE TITLE
unblock ctpool.net

### ISSUE THREAD

**Issue by cryptocompanyoy** [phantom/blocklist#982]
Hello

It seems that our domain name ctpool.net got in your blocklist, please review it manually and remove it from the listing. 

Our product can be downloaded from https://play.google.com/store/apps/details?id=net.ctpool
![ctpool](https://github.com/phantom/blocklist/assets/127208895/b9d0c879-8c7d-42b1-8d3f-1ae2ea7958f4)

CryptoCompany Team

**Comment by cryptocompanyoy** [comment]
Any update?

**Comment by Harii94** [comment]
Apologies for the delay in response, please send an email to review@blowfish.xyz for further investigation.
