### ISSUE TITLE
lormhole.com falsely blocked

### ISSUE THREAD

**Issue by emmsixx** [phantom/blocklist#984]
Was contracted by the memecoin's devs to make a website. The website has no wallet adapters anywhere in the code and is simply a gag.

Site has been falsely flagged, would greatly appreciate if you resolve it in a timely manner.
Domain: lormhole.com

Kind regards,
M6

**Comment by verata-veritatis** [comment]
um.
![image](https://github.com/phantom/blocklist/assets/9677388/553606d7-49da-49e4-a75e-2b081742de16)

**Comment by emmsixx** [comment]
i misspelled the URL, just fixed it
