### ISSUE TITLE
translate.goog falsely blocked again

### ISSUE THREAD

**Issue by uralandushka** [phantom/blocklist#986]
translate.goog is a google translate service blocked falsely.

It was same issue before which was resolved for unblocking this service https://github.com/phantom/blocklist/issues/677
but now it blocked again.

**Comment by Harii94** [comment]
Hi @uralandushka, this issue has been resolved and the site has been added to the whitelist. Could you please confirm if the problem is solved?

**Comment by uralandushka** [comment]
yes, now it work again
